/*
 * This file is generated by jOOQ.
*/
package com.showka.table.public_.tables;


import com.showka.table.public_.Keys;
import com.showka.table.public_.Public;
import com.showka.table.public_.tables.records.J_SHOHIN_IDO_URIAGE_RECORD;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class J_SHOHIN_IDO_URIAGE extends TableImpl<J_SHOHIN_IDO_URIAGE_RECORD> {

    private static final long serialVersionUID = -2044254125;

    /**
     * The reference instance of <code>PUBLIC.J_SHOHIN_IDO_URIAGE</code>
     */
    public static final J_SHOHIN_IDO_URIAGE j_shohin_ido_uriage = new J_SHOHIN_IDO_URIAGE();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<J_SHOHIN_IDO_URIAGE_RECORD> getRecordType() {
        return J_SHOHIN_IDO_URIAGE_RECORD.class;
    }

    /**
     * The column <code>PUBLIC.J_SHOHIN_IDO_URIAGE.SHOHIN_IDO_ID</code>.
     */
    public final TableField<J_SHOHIN_IDO_URIAGE_RECORD, String> shohin_ido_id = createField("SHOHIN_IDO_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.J_SHOHIN_IDO_URIAGE.CREATE_FUNCTION</code>.
     */
    public final TableField<J_SHOHIN_IDO_URIAGE_RECORD, String> create_function = createField("CREATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.J_SHOHIN_IDO_URIAGE.CREATE_TIMESTAMP</code>.
     */
    public final TableField<J_SHOHIN_IDO_URIAGE_RECORD, LocalDateTime> create_timestamp = createField("CREATE_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.J_SHOHIN_IDO_URIAGE.CREATE_USER_ID</code>.
     */
    public final TableField<J_SHOHIN_IDO_URIAGE_RECORD, String> create_user_id = createField("CREATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.J_SHOHIN_IDO_URIAGE.RECORD_ID</code>.
     */
    public final TableField<J_SHOHIN_IDO_URIAGE_RECORD, String> record_id = createField("RECORD_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.J_SHOHIN_IDO_URIAGE.UPDATE_FUNCTION</code>.
     */
    public final TableField<J_SHOHIN_IDO_URIAGE_RECORD, String> update_function = createField("UPDATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.J_SHOHIN_IDO_URIAGE.UPDATE_TIMESTAMP</code>.
     */
    public final TableField<J_SHOHIN_IDO_URIAGE_RECORD, LocalDateTime> update_timestamp = createField("UPDATE_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.J_SHOHIN_IDO_URIAGE.UPDATE_USER_ID</code>.
     */
    public final TableField<J_SHOHIN_IDO_URIAGE_RECORD, String> update_user_id = createField("UPDATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.J_SHOHIN_IDO_URIAGE.VERSION</code>.
     */
    public final TableField<J_SHOHIN_IDO_URIAGE_RECORD, Integer> version = createField("VERSION", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>PUBLIC.J_SHOHIN_IDO_URIAGE.URIAGE_ID</code>.
     */
    public final TableField<J_SHOHIN_IDO_URIAGE_RECORD, String> uriage_id = createField("URIAGE_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.J_SHOHIN_IDO_URIAGE</code> table reference
     */
    public J_SHOHIN_IDO_URIAGE() {
        this(DSL.name("J_SHOHIN_IDO_URIAGE"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.J_SHOHIN_IDO_URIAGE</code> table reference
     */
    public J_SHOHIN_IDO_URIAGE(String alias) {
        this(DSL.name(alias), j_shohin_ido_uriage);
    }

    /**
     * Create an aliased <code>PUBLIC.J_SHOHIN_IDO_URIAGE</code> table reference
     */
    public J_SHOHIN_IDO_URIAGE(Name alias) {
        this(alias, j_shohin_ido_uriage);
    }

    private J_SHOHIN_IDO_URIAGE(Name alias, Table<J_SHOHIN_IDO_URIAGE_RECORD> aliased) {
        this(alias, aliased, null);
    }

    private J_SHOHIN_IDO_URIAGE(Name alias, Table<J_SHOHIN_IDO_URIAGE_RECORD> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<J_SHOHIN_IDO_URIAGE_RECORD> getPrimaryKey() {
        return Keys.CONSTRAINT_2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<J_SHOHIN_IDO_URIAGE_RECORD>> getKeys() {
        return Arrays.<UniqueKey<J_SHOHIN_IDO_URIAGE_RECORD>>asList(Keys.CONSTRAINT_2, Keys.UK_CFXPYU7SU1PV9WO2AUTSACG0I);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<J_SHOHIN_IDO_URIAGE_RECORD, ?>> getReferences() {
        return Arrays.<ForeignKey<J_SHOHIN_IDO_URIAGE_RECORD, ?>>asList(Keys.FK5DYE4WJDXP0GYE240FAHRWIYY, Keys.FKTFEGJY18RHN048QJ3D5GH9SRV);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public J_SHOHIN_IDO_URIAGE as(String alias) {
        return new J_SHOHIN_IDO_URIAGE(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public J_SHOHIN_IDO_URIAGE as(Name alias) {
        return new J_SHOHIN_IDO_URIAGE(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public J_SHOHIN_IDO_URIAGE rename(String name) {
        return new J_SHOHIN_IDO_URIAGE(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public J_SHOHIN_IDO_URIAGE rename(Name name) {
        return new J_SHOHIN_IDO_URIAGE(name, null);
    }
}
