/*
 * This file is generated by jOOQ.
*/
package com.showka.table.public_.tables;


import com.showka.table.public_.Keys;
import com.showka.table.public_.Public;
import com.showka.table.public_.tables.records.J_URIKAKE_SEIKYU_RECORD;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class J_URIKAKE_SEIKYU extends TableImpl<J_URIKAKE_SEIKYU_RECORD> {

    private static final long serialVersionUID = -1247132478;

    /**
     * The reference instance of <code>PUBLIC.J_URIKAKE_SEIKYU</code>
     */
    public static final J_URIKAKE_SEIKYU j_urikake_seikyu = new J_URIKAKE_SEIKYU();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<J_URIKAKE_SEIKYU_RECORD> getRecordType() {
        return J_URIKAKE_SEIKYU_RECORD.class;
    }

    /**
     * The column <code>PUBLIC.J_URIKAKE_SEIKYU.URIKAKE_ID</code>.
     */
    public final TableField<J_URIKAKE_SEIKYU_RECORD, String> urikake_id = createField("URIKAKE_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.J_URIKAKE_SEIKYU.CREATE_FUNCTION</code>.
     */
    public final TableField<J_URIKAKE_SEIKYU_RECORD, String> create_function = createField("CREATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.J_URIKAKE_SEIKYU.CREATE_TIMESTAMP</code>.
     */
    public final TableField<J_URIKAKE_SEIKYU_RECORD, LocalDateTime> create_timestamp = createField("CREATE_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.J_URIKAKE_SEIKYU.CREATE_USER_ID</code>.
     */
    public final TableField<J_URIKAKE_SEIKYU_RECORD, String> create_user_id = createField("CREATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.J_URIKAKE_SEIKYU.RECORD_ID</code>.
     */
    public final TableField<J_URIKAKE_SEIKYU_RECORD, String> record_id = createField("RECORD_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.J_URIKAKE_SEIKYU.UPDATE_FUNCTION</code>.
     */
    public final TableField<J_URIKAKE_SEIKYU_RECORD, String> update_function = createField("UPDATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.J_URIKAKE_SEIKYU.UPDATE_TIMESTAMP</code>.
     */
    public final TableField<J_URIKAKE_SEIKYU_RECORD, LocalDateTime> update_timestamp = createField("UPDATE_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.J_URIKAKE_SEIKYU.UPDATE_USER_ID</code>.
     */
    public final TableField<J_URIKAKE_SEIKYU_RECORD, String> update_user_id = createField("UPDATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.J_URIKAKE_SEIKYU.VERSION</code>.
     */
    public final TableField<J_URIKAKE_SEIKYU_RECORD, Integer> version = createField("VERSION", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>PUBLIC.J_URIKAKE_SEIKYU.SEIKYU_ID</code>.
     */
    public final TableField<J_URIKAKE_SEIKYU_RECORD, String> seikyu_id = createField("SEIKYU_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.J_URIKAKE_SEIKYU</code> table reference
     */
    public J_URIKAKE_SEIKYU() {
        this(DSL.name("J_URIKAKE_SEIKYU"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.J_URIKAKE_SEIKYU</code> table reference
     */
    public J_URIKAKE_SEIKYU(String alias) {
        this(DSL.name(alias), j_urikake_seikyu);
    }

    /**
     * Create an aliased <code>PUBLIC.J_URIKAKE_SEIKYU</code> table reference
     */
    public J_URIKAKE_SEIKYU(Name alias) {
        this(alias, j_urikake_seikyu);
    }

    private J_URIKAKE_SEIKYU(Name alias, Table<J_URIKAKE_SEIKYU_RECORD> aliased) {
        this(alias, aliased, null);
    }

    private J_URIKAKE_SEIKYU(Name alias, Table<J_URIKAKE_SEIKYU_RECORD> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<J_URIKAKE_SEIKYU_RECORD> getPrimaryKey() {
        return Keys.CONSTRAINT_6B;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<J_URIKAKE_SEIKYU_RECORD>> getKeys() {
        return Arrays.<UniqueKey<J_URIKAKE_SEIKYU_RECORD>>asList(Keys.CONSTRAINT_6B, Keys.UK_4Q852GGA0X74LAO0IDIAB7PB1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public J_URIKAKE_SEIKYU as(String alias) {
        return new J_URIKAKE_SEIKYU(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public J_URIKAKE_SEIKYU as(Name alias) {
        return new J_URIKAKE_SEIKYU(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public J_URIKAKE_SEIKYU rename(String name) {
        return new J_URIKAKE_SEIKYU(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public J_URIKAKE_SEIKYU rename(Name name) {
        return new J_URIKAKE_SEIKYU(name, null);
    }
}
