/*
 * This file is generated by jOOQ.
*/
package com.showka.table.public_.tables;


import com.showka.table.public_.Indexes;
import com.showka.table.public_.Keys;
import com.showka.table.public_.Public;
import com.showka.table.public_.tables.records.M_BUSHO_RECORD;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class M_BUSHO extends TableImpl<M_BUSHO_RECORD> {

    private static final long serialVersionUID = -473619064;

    /**
     * The reference instance of <code>PUBLIC.M_BUSHO</code>
     */
    public static final M_BUSHO m_busho = new M_BUSHO();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<M_BUSHO_RECORD> getRecordType() {
        return M_BUSHO_RECORD.class;
    }

    /**
     * The column <code>PUBLIC.M_BUSHO.CODE</code>.
     */
    public final TableField<M_BUSHO_RECORD, String> CODE = createField("CODE", org.jooq.impl.SQLDataType.VARCHAR(4).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.M_BUSHO.CREATE_FUNCTION</code>.
     */
    public final TableField<M_BUSHO_RECORD, String> CREATE_FUNCTION = createField("CREATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.M_BUSHO.CREATE_TIMESTAMP</code>.
     */
    public final TableField<M_BUSHO_RECORD, Timestamp> CREATE_TIMESTAMP = createField("CREATE_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>PUBLIC.M_BUSHO.CREATE_USER_ID</code>.
     */
    public final TableField<M_BUSHO_RECORD, String> CREATE_USER_ID = createField("CREATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.M_BUSHO.RECORD_ID</code>.
     */
    public final TableField<M_BUSHO_RECORD, String> RECORD_ID = createField("RECORD_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.M_BUSHO.UPDATE_FUNCTION</code>.
     */
    public final TableField<M_BUSHO_RECORD, String> UPDATE_FUNCTION = createField("UPDATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.M_BUSHO.UPDATE_TIMESTAMP</code>.
     */
    public final TableField<M_BUSHO_RECORD, Timestamp> UPDATE_TIMESTAMP = createField("UPDATE_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>PUBLIC.M_BUSHO.UPDATE_USER_ID</code>.
     */
    public final TableField<M_BUSHO_RECORD, String> UPDATE_USER_ID = createField("UPDATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.M_BUSHO.VERSION</code>.
     */
    public final TableField<M_BUSHO_RECORD, Integer> VERSION = createField("VERSION", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>PUBLIC.M_BUSHO.BUSHO_KUBUN</code>.
     */
    public final TableField<M_BUSHO_RECORD, String> BUSHO_KUBUN = createField("BUSHO_KUBUN", org.jooq.impl.SQLDataType.VARCHAR(2).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.M_BUSHO.JIGYO_KUBUN</code>.
     */
    public final TableField<M_BUSHO_RECORD, String> JIGYO_KUBUN = createField("JIGYO_KUBUN", org.jooq.impl.SQLDataType.VARCHAR(2).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.M_BUSHO.NAME</code>.
     */
    public final TableField<M_BUSHO_RECORD, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.M_BUSHO</code> table reference
     */
    public M_BUSHO() {
        this(DSL.name("M_BUSHO"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.M_BUSHO</code> table reference
     */
    public M_BUSHO(String alias) {
        this(DSL.name(alias), m_busho);
    }

    /**
     * Create an aliased <code>PUBLIC.M_BUSHO</code> table reference
     */
    public M_BUSHO(Name alias) {
        this(alias, m_busho);
    }

    private M_BUSHO(Name alias, Table<M_BUSHO_RECORD> aliased) {
        this(alias, aliased, null);
    }

    private M_BUSHO(Name alias, Table<M_BUSHO_RECORD> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_8, Indexes.UK_5BY1GUP4TXK8FK16KGF8MPF38_INDEX_8);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<M_BUSHO_RECORD> getPrimaryKey() {
        return Keys.CONSTRAINT_8;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<M_BUSHO_RECORD>> getKeys() {
        return Arrays.<UniqueKey<M_BUSHO_RECORD>>asList(Keys.CONSTRAINT_8, Keys.UK_5BY1GUP4TXK8FK16KGF8MPF38);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public M_BUSHO as(String alias) {
        return new M_BUSHO(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public M_BUSHO as(Name alias) {
        return new M_BUSHO(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public M_BUSHO rename(String name) {
        return new M_BUSHO(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public M_BUSHO rename(Name name) {
        return new M_BUSHO(name, null);
    }
}
