/*
 * This file is generated by jOOQ.
*/
package com.showka.table.public_.tables;


import com.showka.table.public_.Keys;
import com.showka.table.public_.Public;
import com.showka.table.public_.tables.records.R_URIAGE_KEIJO_RECORD;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class R_URIAGE_KEIJO extends TableImpl<R_URIAGE_KEIJO_RECORD> {

    private static final long serialVersionUID = 1622949494;

    /**
     * The reference instance of <code>PUBLIC.R_URIAGE_KEIJO</code>
     */
    public static final R_URIAGE_KEIJO r_uriage_keijo = new R_URIAGE_KEIJO();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<R_URIAGE_KEIJO_RECORD> getRecordType() {
        return R_URIAGE_KEIJO_RECORD.class;
    }

    /**
     * The column <code>PUBLIC.R_URIAGE_KEIJO.URIAGE_RIREKI_ID</code>.
     */
    public final TableField<R_URIAGE_KEIJO_RECORD, String> uriage_rireki_id = createField("URIAGE_RIREKI_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE_KEIJO.CREATE_FUNCTION</code>.
     */
    public final TableField<R_URIAGE_KEIJO_RECORD, String> create_function = createField("CREATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE_KEIJO.CREATE_TIMESTAMP</code>.
     */
    public final TableField<R_URIAGE_KEIJO_RECORD, LocalDateTime> create_timestamp = createField("CREATE_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE_KEIJO.CREATE_USER_ID</code>.
     */
    public final TableField<R_URIAGE_KEIJO_RECORD, String> create_user_id = createField("CREATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE_KEIJO.RECORD_ID</code>.
     */
    public final TableField<R_URIAGE_KEIJO_RECORD, String> record_id = createField("RECORD_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE_KEIJO.UPDATE_FUNCTION</code>.
     */
    public final TableField<R_URIAGE_KEIJO_RECORD, String> update_function = createField("UPDATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE_KEIJO.UPDATE_TIMESTAMP</code>.
     */
    public final TableField<R_URIAGE_KEIJO_RECORD, LocalDateTime> update_timestamp = createField("UPDATE_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE_KEIJO.UPDATE_USER_ID</code>.
     */
    public final TableField<R_URIAGE_KEIJO_RECORD, String> update_user_id = createField("UPDATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE_KEIJO.VERSION</code>.
     */
    public final TableField<R_URIAGE_KEIJO_RECORD, Integer> version = createField("VERSION", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE_KEIJO.BUSHO_ID</code>.
     */
    public final TableField<R_URIAGE_KEIJO_RECORD, String> busho_id = createField("BUSHO_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.R_URIAGE_KEIJO</code> table reference
     */
    public R_URIAGE_KEIJO() {
        this(DSL.name("R_URIAGE_KEIJO"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.R_URIAGE_KEIJO</code> table reference
     */
    public R_URIAGE_KEIJO(String alias) {
        this(DSL.name(alias), r_uriage_keijo);
    }

    /**
     * Create an aliased <code>PUBLIC.R_URIAGE_KEIJO</code> table reference
     */
    public R_URIAGE_KEIJO(Name alias) {
        this(alias, r_uriage_keijo);
    }

    private R_URIAGE_KEIJO(Name alias, Table<R_URIAGE_KEIJO_RECORD> aliased) {
        this(alias, aliased, null);
    }

    private R_URIAGE_KEIJO(Name alias, Table<R_URIAGE_KEIJO_RECORD> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<R_URIAGE_KEIJO_RECORD> getPrimaryKey() {
        return Keys.CONSTRAINT_21;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<R_URIAGE_KEIJO_RECORD>> getKeys() {
        return Arrays.<UniqueKey<R_URIAGE_KEIJO_RECORD>>asList(Keys.CONSTRAINT_21, Keys.UK_68YGMNT83I8TJ9VCTJUJ7DNOH);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<R_URIAGE_KEIJO_RECORD, ?>> getReferences() {
        return Arrays.<ForeignKey<R_URIAGE_KEIJO_RECORD, ?>>asList(Keys.FKH0U4RF1JDXDX32VNB3O7FU8PH, Keys.FK88YWWSH8XTTSGK28INR0I5POH);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public R_URIAGE_KEIJO as(String alias) {
        return new R_URIAGE_KEIJO(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public R_URIAGE_KEIJO as(Name alias) {
        return new R_URIAGE_KEIJO(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public R_URIAGE_KEIJO rename(String name) {
        return new R_URIAGE_KEIJO(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public R_URIAGE_KEIJO rename(Name name) {
        return new R_URIAGE_KEIJO(name, null);
    }
}
