/*
 * This file is generated by jOOQ.
*/
package com.showka.table.public_.tables;


import com.showka.table.public_.Keys;
import com.showka.table.public_.Public;
import com.showka.table.public_.tables.records.R_URIAGE_KEIJO_TEISEI_RECORD;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class R_URIAGE_KEIJO_TEISEI extends TableImpl<R_URIAGE_KEIJO_TEISEI_RECORD> {

    private static final long serialVersionUID = -1466264786;

    /**
     * The reference instance of <code>PUBLIC.R_URIAGE_KEIJO_TEISEI</code>
     */
    public static final R_URIAGE_KEIJO_TEISEI r_uriage_keijo_teisei = new R_URIAGE_KEIJO_TEISEI();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<R_URIAGE_KEIJO_TEISEI_RECORD> getRecordType() {
        return R_URIAGE_KEIJO_TEISEI_RECORD.class;
    }

    /**
     * The column <code>PUBLIC.R_URIAGE_KEIJO_TEISEI.URIAGE_KEIJO_ID</code>.
     */
    public final TableField<R_URIAGE_KEIJO_TEISEI_RECORD, String> uriage_keijo_id = createField("URIAGE_KEIJO_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE_KEIJO_TEISEI.CREATE_FUNCTION</code>.
     */
    public final TableField<R_URIAGE_KEIJO_TEISEI_RECORD, String> create_function = createField("CREATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE_KEIJO_TEISEI.CREATE_TIMESTAMP</code>.
     */
    public final TableField<R_URIAGE_KEIJO_TEISEI_RECORD, LocalDateTime> create_timestamp = createField("CREATE_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE_KEIJO_TEISEI.CREATE_USER_ID</code>.
     */
    public final TableField<R_URIAGE_KEIJO_TEISEI_RECORD, String> create_user_id = createField("CREATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE_KEIJO_TEISEI.RECORD_ID</code>.
     */
    public final TableField<R_URIAGE_KEIJO_TEISEI_RECORD, String> record_id = createField("RECORD_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE_KEIJO_TEISEI.UPDATE_FUNCTION</code>.
     */
    public final TableField<R_URIAGE_KEIJO_TEISEI_RECORD, String> update_function = createField("UPDATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE_KEIJO_TEISEI.UPDATE_TIMESTAMP</code>.
     */
    public final TableField<R_URIAGE_KEIJO_TEISEI_RECORD, LocalDateTime> update_timestamp = createField("UPDATE_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE_KEIJO_TEISEI.UPDATE_USER_ID</code>.
     */
    public final TableField<R_URIAGE_KEIJO_TEISEI_RECORD, String> update_user_id = createField("UPDATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE_KEIJO_TEISEI.VERSION</code>.
     */
    public final TableField<R_URIAGE_KEIJO_TEISEI_RECORD, Integer> version = createField("VERSION", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE_KEIJO_TEISEI.URIAGE_RIREKI_ID</code>.
     */
    public final TableField<R_URIAGE_KEIJO_TEISEI_RECORD, String> uriage_rireki_id = createField("URIAGE_RIREKI_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.R_URIAGE_KEIJO_TEISEI</code> table reference
     */
    public R_URIAGE_KEIJO_TEISEI() {
        this(DSL.name("R_URIAGE_KEIJO_TEISEI"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.R_URIAGE_KEIJO_TEISEI</code> table reference
     */
    public R_URIAGE_KEIJO_TEISEI(String alias) {
        this(DSL.name(alias), r_uriage_keijo_teisei);
    }

    /**
     * Create an aliased <code>PUBLIC.R_URIAGE_KEIJO_TEISEI</code> table reference
     */
    public R_URIAGE_KEIJO_TEISEI(Name alias) {
        this(alias, r_uriage_keijo_teisei);
    }

    private R_URIAGE_KEIJO_TEISEI(Name alias, Table<R_URIAGE_KEIJO_TEISEI_RECORD> aliased) {
        this(alias, aliased, null);
    }

    private R_URIAGE_KEIJO_TEISEI(Name alias, Table<R_URIAGE_KEIJO_TEISEI_RECORD> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<R_URIAGE_KEIJO_TEISEI_RECORD> getPrimaryKey() {
        return Keys.CONSTRAINT_F;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<R_URIAGE_KEIJO_TEISEI_RECORD>> getKeys() {
        return Arrays.<UniqueKey<R_URIAGE_KEIJO_TEISEI_RECORD>>asList(Keys.CONSTRAINT_F, Keys.UK_5FQTU9VF1ITABDUFF88E46ALY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<R_URIAGE_KEIJO_TEISEI_RECORD, ?>> getReferences() {
        return Arrays.<ForeignKey<R_URIAGE_KEIJO_TEISEI_RECORD, ?>>asList(Keys.FKMHVV9FBVRGL5J34H408W7LXQF, Keys.FKJ7YBAXR6IN6VUA1KLM2I10YEK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public R_URIAGE_KEIJO_TEISEI as(String alias) {
        return new R_URIAGE_KEIJO_TEISEI(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public R_URIAGE_KEIJO_TEISEI as(Name alias) {
        return new R_URIAGE_KEIJO_TEISEI(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public R_URIAGE_KEIJO_TEISEI rename(String name) {
        return new R_URIAGE_KEIJO_TEISEI(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public R_URIAGE_KEIJO_TEISEI rename(Name name) {
        return new R_URIAGE_KEIJO_TEISEI(name, null);
    }
}
