/*
 * This file is generated by jOOQ.
*/
package com.showka.table.public_.tables;


import com.showka.table.public_.Keys;
import com.showka.table.public_.Public;
import com.showka.table.public_.tables.records.R_URIAGE_RECORD;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class R_URIAGE extends TableImpl<R_URIAGE_RECORD> {

    private static final long serialVersionUID = -1593000163;

    /**
     * The reference instance of <code>PUBLIC.R_URIAGE</code>
     */
    public static final R_URIAGE r_uriage = new R_URIAGE();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<R_URIAGE_RECORD> getRecordType() {
        return R_URIAGE_RECORD.class;
    }

    /**
     * The column <code>PUBLIC.R_URIAGE.KEIJO_DATE</code>.
     */
    public final TableField<R_URIAGE_RECORD, LocalDateTime> keijo_date = createField("KEIJO_DATE", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE.URIAGE_ID</code>.
     */
    public final TableField<R_URIAGE_RECORD, String> uriage_id = createField("URIAGE_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE.CREATE_FUNCTION</code>.
     */
    public final TableField<R_URIAGE_RECORD, String> create_function = createField("CREATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE.CREATE_TIMESTAMP</code>.
     */
    public final TableField<R_URIAGE_RECORD, LocalDateTime> create_timestamp = createField("CREATE_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE.CREATE_USER_ID</code>.
     */
    public final TableField<R_URIAGE_RECORD, String> create_user_id = createField("CREATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE.RECORD_ID</code>.
     */
    public final TableField<R_URIAGE_RECORD, String> record_id = createField("RECORD_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE.UPDATE_FUNCTION</code>.
     */
    public final TableField<R_URIAGE_RECORD, String> update_function = createField("UPDATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE.UPDATE_TIMESTAMP</code>.
     */
    public final TableField<R_URIAGE_RECORD, LocalDateTime> update_timestamp = createField("UPDATE_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE.UPDATE_USER_ID</code>.
     */
    public final TableField<R_URIAGE_RECORD, String> update_user_id = createField("UPDATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE.VERSION</code>.
     */
    public final TableField<R_URIAGE_RECORD, Integer> version = createField("VERSION", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE.HANBAI_KUBUN</code>.
     */
    public final TableField<R_URIAGE_RECORD, String> hanbai_kubun = createField("HANBAI_KUBUN", org.jooq.impl.SQLDataType.VARCHAR(2).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE.SHOHIZEIRITSU</code>.
     */
    public final TableField<R_URIAGE_RECORD, Double> shohizeiritsu = createField("SHOHIZEIRITSU", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.R_URIAGE.URIAGE_DATE</code>.
     */
    public final TableField<R_URIAGE_RECORD, LocalDateTime> uriage_date = createField("URIAGE_DATE", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.R_URIAGE</code> table reference
     */
    public R_URIAGE() {
        this(DSL.name("R_URIAGE"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.R_URIAGE</code> table reference
     */
    public R_URIAGE(String alias) {
        this(DSL.name(alias), r_uriage);
    }

    /**
     * Create an aliased <code>PUBLIC.R_URIAGE</code> table reference
     */
    public R_URIAGE(Name alias) {
        this(alias, r_uriage);
    }

    private R_URIAGE(Name alias, Table<R_URIAGE_RECORD> aliased) {
        this(alias, aliased, null);
    }

    private R_URIAGE(Name alias, Table<R_URIAGE_RECORD> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<R_URIAGE_RECORD> getPrimaryKey() {
        return Keys.CONSTRAINT_7D;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<R_URIAGE_RECORD>> getKeys() {
        return Arrays.<UniqueKey<R_URIAGE_RECORD>>asList(Keys.CONSTRAINT_7D, Keys.UK_3PUXJQQMYDE93SCH3O89I3UV7);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<R_URIAGE_RECORD, ?>> getReferences() {
        return Arrays.<ForeignKey<R_URIAGE_RECORD, ?>>asList(Keys.FKPA4RJI1OV770T37MNYHLVHTY1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public R_URIAGE as(String alias) {
        return new R_URIAGE(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public R_URIAGE as(Name alias) {
        return new R_URIAGE(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public R_URIAGE rename(String name) {
        return new R_URIAGE(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public R_URIAGE rename(Name name) {
        return new R_URIAGE(name, null);
    }
}
