/*
 * This file is generated by jOOQ.
*/
package com.showka.table.public_.tables;


import com.showka.table.public_.Keys;
import com.showka.table.public_.Public;
import com.showka.table.public_.tables.records.S_URIKAKE_SEIKYU_DONE_RECORD;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S_URIKAKE_SEIKYU_DONE extends TableImpl<S_URIKAKE_SEIKYU_DONE_RECORD> {

    private static final long serialVersionUID = 1414132815;

    /**
     * The reference instance of <code>PUBLIC.S_URIKAKE_SEIKYU_DONE</code>
     */
    public static final S_URIKAKE_SEIKYU_DONE s_urikake_seikyu_done = new S_URIKAKE_SEIKYU_DONE();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<S_URIKAKE_SEIKYU_DONE_RECORD> getRecordType() {
        return S_URIKAKE_SEIKYU_DONE_RECORD.class;
    }

    /**
     * The column <code>PUBLIC.S_URIKAKE_SEIKYU_DONE.URIKAKE_ID</code>.
     */
    public final TableField<S_URIKAKE_SEIKYU_DONE_RECORD, String> urikake_id = createField("URIKAKE_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.S_URIKAKE_SEIKYU_DONE.CREATE_FUNCTION</code>.
     */
    public final TableField<S_URIKAKE_SEIKYU_DONE_RECORD, String> create_function = createField("CREATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.S_URIKAKE_SEIKYU_DONE.CREATE_TIMESTAMP</code>.
     */
    public final TableField<S_URIKAKE_SEIKYU_DONE_RECORD, LocalDateTime> create_timestamp = createField("CREATE_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.S_URIKAKE_SEIKYU_DONE.CREATE_USER_ID</code>.
     */
    public final TableField<S_URIKAKE_SEIKYU_DONE_RECORD, String> create_user_id = createField("CREATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.S_URIKAKE_SEIKYU_DONE.RECORD_ID</code>.
     */
    public final TableField<S_URIKAKE_SEIKYU_DONE_RECORD, String> record_id = createField("RECORD_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.S_URIKAKE_SEIKYU_DONE.UPDATE_FUNCTION</code>.
     */
    public final TableField<S_URIKAKE_SEIKYU_DONE_RECORD, String> update_function = createField("UPDATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.S_URIKAKE_SEIKYU_DONE.UPDATE_TIMESTAMP</code>.
     */
    public final TableField<S_URIKAKE_SEIKYU_DONE_RECORD, LocalDateTime> update_timestamp = createField("UPDATE_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.S_URIKAKE_SEIKYU_DONE.UPDATE_USER_ID</code>.
     */
    public final TableField<S_URIKAKE_SEIKYU_DONE_RECORD, String> update_user_id = createField("UPDATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.S_URIKAKE_SEIKYU_DONE.VERSION</code>.
     */
    public final TableField<S_URIKAKE_SEIKYU_DONE_RECORD, Integer> version = createField("VERSION", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>PUBLIC.S_URIKAKE_SEIKYU_DONE.SEIKYU_ID</code>.
     */
    public final TableField<S_URIKAKE_SEIKYU_DONE_RECORD, String> seikyu_id = createField("SEIKYU_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.S_URIKAKE_SEIKYU_DONE</code> table reference
     */
    public S_URIKAKE_SEIKYU_DONE() {
        this(DSL.name("S_URIKAKE_SEIKYU_DONE"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.S_URIKAKE_SEIKYU_DONE</code> table reference
     */
    public S_URIKAKE_SEIKYU_DONE(String alias) {
        this(DSL.name(alias), s_urikake_seikyu_done);
    }

    /**
     * Create an aliased <code>PUBLIC.S_URIKAKE_SEIKYU_DONE</code> table reference
     */
    public S_URIKAKE_SEIKYU_DONE(Name alias) {
        this(alias, s_urikake_seikyu_done);
    }

    private S_URIKAKE_SEIKYU_DONE(Name alias, Table<S_URIKAKE_SEIKYU_DONE_RECORD> aliased) {
        this(alias, aliased, null);
    }

    private S_URIKAKE_SEIKYU_DONE(Name alias, Table<S_URIKAKE_SEIKYU_DONE_RECORD> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<S_URIKAKE_SEIKYU_DONE_RECORD> getPrimaryKey() {
        return Keys.CONSTRAINT_50;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<S_URIKAKE_SEIKYU_DONE_RECORD>> getKeys() {
        return Arrays.<UniqueKey<S_URIKAKE_SEIKYU_DONE_RECORD>>asList(Keys.CONSTRAINT_50, Keys.UK_HGYB1F2BULW8F6P5LNW5GIGT4);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<S_URIKAKE_SEIKYU_DONE_RECORD, ?>> getReferences() {
        return Arrays.<ForeignKey<S_URIKAKE_SEIKYU_DONE_RECORD, ?>>asList(Keys.FKE5CMEL9P0EG4UOHYTK5WON16N, Keys.FKQ3D3EH9H7F43L7AGT956MKNRP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public S_URIKAKE_SEIKYU_DONE as(String alias) {
        return new S_URIKAKE_SEIKYU_DONE(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public S_URIKAKE_SEIKYU_DONE as(Name alias) {
        return new S_URIKAKE_SEIKYU_DONE(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public S_URIKAKE_SEIKYU_DONE rename(String name) {
        return new S_URIKAKE_SEIKYU_DONE(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public S_URIKAKE_SEIKYU_DONE rename(Name name) {
        return new S_URIKAKE_SEIKYU_DONE(name, null);
    }
}
