/*
 * This file is generated by jOOQ.
*/
package com.showka.table.public_.tables;


import com.showka.table.public_.Keys;
import com.showka.table.public_.Public;
import com.showka.table.public_.tables.records.T_FIRM_BANK_FURIKOMI_RECORD;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T_FIRM_BANK_FURIKOMI extends TableImpl<T_FIRM_BANK_FURIKOMI_RECORD> {

    private static final long serialVersionUID = 400282103;

    /**
     * The reference instance of <code>PUBLIC.T_FIRM_BANK_FURIKOMI</code>
     */
    public static final T_FIRM_BANK_FURIKOMI t_firm_bank_furikomi = new T_FIRM_BANK_FURIKOMI();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<T_FIRM_BANK_FURIKOMI_RECORD> getRecordType() {
        return T_FIRM_BANK_FURIKOMI_RECORD.class;
    }

    /**
     * The column <code>PUBLIC.T_FIRM_BANK_FURIKOMI.TRANSMISSION_DATE</code>.
     */
    public final TableField<T_FIRM_BANK_FURIKOMI_RECORD, LocalDateTime> transmission_date = createField("TRANSMISSION_DATE", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_FIRM_BANK_FURIKOMI.TRANSMISSION_NUMBER</code>.
     */
    public final TableField<T_FIRM_BANK_FURIKOMI_RECORD, Integer> transmission_number = createField("TRANSMISSION_NUMBER", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_FIRM_BANK_FURIKOMI.CREATE_FUNCTION</code>.
     */
    public final TableField<T_FIRM_BANK_FURIKOMI_RECORD, String> create_function = createField("CREATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.T_FIRM_BANK_FURIKOMI.CREATE_TIMESTAMP</code>.
     */
    public final TableField<T_FIRM_BANK_FURIKOMI_RECORD, LocalDateTime> create_timestamp = createField("CREATE_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.T_FIRM_BANK_FURIKOMI.CREATE_USER_ID</code>.
     */
    public final TableField<T_FIRM_BANK_FURIKOMI_RECORD, String> create_user_id = createField("CREATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.T_FIRM_BANK_FURIKOMI.RECORD_ID</code>.
     */
    public final TableField<T_FIRM_BANK_FURIKOMI_RECORD, String> record_id = createField("RECORD_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_FIRM_BANK_FURIKOMI.UPDATE_FUNCTION</code>.
     */
    public final TableField<T_FIRM_BANK_FURIKOMI_RECORD, String> update_function = createField("UPDATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.T_FIRM_BANK_FURIKOMI.UPDATE_TIMESTAMP</code>.
     */
    public final TableField<T_FIRM_BANK_FURIKOMI_RECORD, LocalDateTime> update_timestamp = createField("UPDATE_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.T_FIRM_BANK_FURIKOMI.UPDATE_USER_ID</code>.
     */
    public final TableField<T_FIRM_BANK_FURIKOMI_RECORD, String> update_user_id = createField("UPDATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.T_FIRM_BANK_FURIKOMI.VERSION</code>.
     */
    public final TableField<T_FIRM_BANK_FURIKOMI_RECORD, Integer> version = createField("VERSION", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>PUBLIC.T_FIRM_BANK_FURIKOMI.ACCOUNT_NUMBER</code>.
     */
    public final TableField<T_FIRM_BANK_FURIKOMI_RECORD, String> account_number = createField("ACCOUNT_NUMBER", org.jooq.impl.SQLDataType.VARCHAR(8).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_FIRM_BANK_FURIKOMI.BANK_CODE</code>.
     */
    public final TableField<T_FIRM_BANK_FURIKOMI_RECORD, String> bank_code = createField("BANK_CODE", org.jooq.impl.SQLDataType.VARCHAR(4).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_FIRM_BANK_FURIKOMI.FURIKOMI_IRAININ_NAME</code>.
     */
    public final TableField<T_FIRM_BANK_FURIKOMI_RECORD, String> furikomi_irainin_name = createField("FURIKOMI_IRAININ_NAME", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_FIRM_BANK_FURIKOMI.KINGAKU</code>.
     */
    public final TableField<T_FIRM_BANK_FURIKOMI_RECORD, Integer> kingaku = createField("KINGAKU", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_FIRM_BANK_FURIKOMI.SETTLEMENT_DATE</code>.
     */
    public final TableField<T_FIRM_BANK_FURIKOMI_RECORD, LocalDateTime> settlement_date = createField("SETTLEMENT_DATE", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.T_FIRM_BANK_FURIKOMI</code> table reference
     */
    public T_FIRM_BANK_FURIKOMI() {
        this(DSL.name("T_FIRM_BANK_FURIKOMI"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.T_FIRM_BANK_FURIKOMI</code> table reference
     */
    public T_FIRM_BANK_FURIKOMI(String alias) {
        this(DSL.name(alias), t_firm_bank_furikomi);
    }

    /**
     * Create an aliased <code>PUBLIC.T_FIRM_BANK_FURIKOMI</code> table reference
     */
    public T_FIRM_BANK_FURIKOMI(Name alias) {
        this(alias, t_firm_bank_furikomi);
    }

    private T_FIRM_BANK_FURIKOMI(Name alias, Table<T_FIRM_BANK_FURIKOMI_RECORD> aliased) {
        this(alias, aliased, null);
    }

    private T_FIRM_BANK_FURIKOMI(Name alias, Table<T_FIRM_BANK_FURIKOMI_RECORD> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<T_FIRM_BANK_FURIKOMI_RECORD> getPrimaryKey() {
        return Keys.CONSTRAINT_1B;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<T_FIRM_BANK_FURIKOMI_RECORD>> getKeys() {
        return Arrays.<UniqueKey<T_FIRM_BANK_FURIKOMI_RECORD>>asList(Keys.CONSTRAINT_1B, Keys.UK_SCNOHX9Y1NGRANOP6YEHAHYWV);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_FIRM_BANK_FURIKOMI as(String alias) {
        return new T_FIRM_BANK_FURIKOMI(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_FIRM_BANK_FURIKOMI as(Name alias) {
        return new T_FIRM_BANK_FURIKOMI(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public T_FIRM_BANK_FURIKOMI rename(String name) {
        return new T_FIRM_BANK_FURIKOMI(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public T_FIRM_BANK_FURIKOMI rename(Name name) {
        return new T_FIRM_BANK_FURIKOMI(name, null);
    }
}
