/*
 * This file is generated by jOOQ.
*/
package com.showka.table.public_.tables;


import com.showka.table.public_.Indexes;
import com.showka.table.public_.Keys;
import com.showka.table.public_.Public;
import com.showka.table.public_.tables.records.T_SHOHIN_ZAIKO_RECORD;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T_SHOHIN_ZAIKO extends TableImpl<T_SHOHIN_ZAIKO_RECORD> {

    private static final long serialVersionUID = -839528310;

    /**
     * The reference instance of <code>PUBLIC.T_SHOHIN_ZAIKO</code>
     */
    public static final T_SHOHIN_ZAIKO t_shohin_zaiko = new T_SHOHIN_ZAIKO();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<T_SHOHIN_ZAIKO_RECORD> getRecordType() {
        return T_SHOHIN_ZAIKO_RECORD.class;
    }

    /**
     * The column <code>PUBLIC.T_SHOHIN_ZAIKO.BUSHO_ID</code>.
     */
    public final TableField<T_SHOHIN_ZAIKO_RECORD, String> BUSHO_ID = createField("BUSHO_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_SHOHIN_ZAIKO.EIGYO_DATE</code>.
     */
    public final TableField<T_SHOHIN_ZAIKO_RECORD, Timestamp> EIGYO_DATE = createField("EIGYO_DATE", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_SHOHIN_ZAIKO.SHOHIN_ID</code>.
     */
    public final TableField<T_SHOHIN_ZAIKO_RECORD, String> SHOHIN_ID = createField("SHOHIN_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_SHOHIN_ZAIKO.CREATE_FUNCTION</code>.
     */
    public final TableField<T_SHOHIN_ZAIKO_RECORD, String> CREATE_FUNCTION = createField("CREATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.T_SHOHIN_ZAIKO.CREATE_TIMESTAMP</code>.
     */
    public final TableField<T_SHOHIN_ZAIKO_RECORD, Timestamp> CREATE_TIMESTAMP = createField("CREATE_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>PUBLIC.T_SHOHIN_ZAIKO.CREATE_USER_ID</code>.
     */
    public final TableField<T_SHOHIN_ZAIKO_RECORD, String> CREATE_USER_ID = createField("CREATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.T_SHOHIN_ZAIKO.RECORD_ID</code>.
     */
    public final TableField<T_SHOHIN_ZAIKO_RECORD, String> RECORD_ID = createField("RECORD_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_SHOHIN_ZAIKO.UPDATE_FUNCTION</code>.
     */
    public final TableField<T_SHOHIN_ZAIKO_RECORD, String> UPDATE_FUNCTION = createField("UPDATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.T_SHOHIN_ZAIKO.UPDATE_TIMESTAMP</code>.
     */
    public final TableField<T_SHOHIN_ZAIKO_RECORD, Timestamp> UPDATE_TIMESTAMP = createField("UPDATE_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>PUBLIC.T_SHOHIN_ZAIKO.UPDATE_USER_ID</code>.
     */
    public final TableField<T_SHOHIN_ZAIKO_RECORD, String> UPDATE_USER_ID = createField("UPDATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.T_SHOHIN_ZAIKO.VERSION</code>.
     */
    public final TableField<T_SHOHIN_ZAIKO_RECORD, Integer> VERSION = createField("VERSION", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>PUBLIC.T_SHOHIN_ZAIKO.NUMBER</code>.
     */
    public final TableField<T_SHOHIN_ZAIKO_RECORD, Integer> NUMBER = createField("NUMBER", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.T_SHOHIN_ZAIKO</code> table reference
     */
    public T_SHOHIN_ZAIKO() {
        this(DSL.name("T_SHOHIN_ZAIKO"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.T_SHOHIN_ZAIKO</code> table reference
     */
    public T_SHOHIN_ZAIKO(String alias) {
        this(DSL.name(alias), t_shohin_zaiko);
    }

    /**
     * Create an aliased <code>PUBLIC.T_SHOHIN_ZAIKO</code> table reference
     */
    public T_SHOHIN_ZAIKO(Name alias) {
        this(alias, t_shohin_zaiko);
    }

    private T_SHOHIN_ZAIKO(Name alias, Table<T_SHOHIN_ZAIKO_RECORD> aliased) {
        this(alias, aliased, null);
    }

    private T_SHOHIN_ZAIKO(Name alias, Table<T_SHOHIN_ZAIKO_RECORD> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FKTKU4TUGX74WKRAT36T4WWNWEB_INDEX_7, Indexes.PRIMARY_KEY_78, Indexes.UK_97I9YEJ178G3KQCKRFJ4GJH0N_INDEX_7);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<T_SHOHIN_ZAIKO_RECORD> getPrimaryKey() {
        return Keys.CONSTRAINT_78;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<T_SHOHIN_ZAIKO_RECORD>> getKeys() {
        return Arrays.<UniqueKey<T_SHOHIN_ZAIKO_RECORD>>asList(Keys.CONSTRAINT_78, Keys.UK_97I9YEJ178G3KQCKRFJ4GJH0N);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<T_SHOHIN_ZAIKO_RECORD, ?>> getReferences() {
        return Arrays.<ForeignKey<T_SHOHIN_ZAIKO_RECORD, ?>>asList(Keys.FKTKU4TUGX74WKRAT36T4WWNWEB);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_SHOHIN_ZAIKO as(String alias) {
        return new T_SHOHIN_ZAIKO(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_SHOHIN_ZAIKO as(Name alias) {
        return new T_SHOHIN_ZAIKO(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public T_SHOHIN_ZAIKO rename(String name) {
        return new T_SHOHIN_ZAIKO(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public T_SHOHIN_ZAIKO rename(Name name) {
        return new T_SHOHIN_ZAIKO(name, null);
    }
}
