/*
 * This file is generated by jOOQ.
*/
package com.showka.table.public_.tables;


import com.showka.table.public_.Keys;
import com.showka.table.public_.Public;
import com.showka.table.public_.tables.records.T_SHUKIN_RECORD;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T_SHUKIN extends TableImpl<T_SHUKIN_RECORD> {

    private static final long serialVersionUID = -1419061747;

    /**
     * The reference instance of <code>PUBLIC.T_SHUKIN</code>
     */
    public static final T_SHUKIN t_shukin = new T_SHUKIN();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<T_SHUKIN_RECORD> getRecordType() {
        return T_SHUKIN_RECORD.class;
    }

    /**
     * The column <code>PUBLIC.T_SHUKIN.NYUKIN_ID</code>.
     */
    public final TableField<T_SHUKIN_RECORD, String> nyukin_id = createField("NYUKIN_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_SHUKIN.CREATE_FUNCTION</code>.
     */
    public final TableField<T_SHUKIN_RECORD, String> create_function = createField("CREATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.T_SHUKIN.CREATE_TIMESTAMP</code>.
     */
    public final TableField<T_SHUKIN_RECORD, LocalDateTime> create_timestamp = createField("CREATE_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.T_SHUKIN.CREATE_USER_ID</code>.
     */
    public final TableField<T_SHUKIN_RECORD, String> create_user_id = createField("CREATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.T_SHUKIN.RECORD_ID</code>.
     */
    public final TableField<T_SHUKIN_RECORD, String> record_id = createField("RECORD_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_SHUKIN.UPDATE_FUNCTION</code>.
     */
    public final TableField<T_SHUKIN_RECORD, String> update_function = createField("UPDATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.T_SHUKIN.UPDATE_TIMESTAMP</code>.
     */
    public final TableField<T_SHUKIN_RECORD, LocalDateTime> update_timestamp = createField("UPDATE_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.T_SHUKIN.UPDATE_USER_ID</code>.
     */
    public final TableField<T_SHUKIN_RECORD, String> update_user_id = createField("UPDATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.T_SHUKIN.VERSION</code>.
     */
    public final TableField<T_SHUKIN_RECORD, Integer> version = createField("VERSION", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>PUBLIC.T_SHUKIN.DENPYO_NUMBER</code>.
     */
    public final TableField<T_SHUKIN_RECORD, String> denpyo_number = createField("DENPYO_NUMBER", org.jooq.impl.SQLDataType.VARCHAR(5).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_SHUKIN.TANTO_SHAIN_ID</code>.
     */
    public final TableField<T_SHUKIN_RECORD, String> tanto_shain_id = createField("TANTO_SHAIN_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.T_SHUKIN</code> table reference
     */
    public T_SHUKIN() {
        this(DSL.name("T_SHUKIN"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.T_SHUKIN</code> table reference
     */
    public T_SHUKIN(String alias) {
        this(DSL.name(alias), t_shukin);
    }

    /**
     * Create an aliased <code>PUBLIC.T_SHUKIN</code> table reference
     */
    public T_SHUKIN(Name alias) {
        this(alias, t_shukin);
    }

    private T_SHUKIN(Name alias, Table<T_SHUKIN_RECORD> aliased) {
        this(alias, aliased, null);
    }

    private T_SHUKIN(Name alias, Table<T_SHUKIN_RECORD> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<T_SHUKIN_RECORD> getPrimaryKey() {
        return Keys.CONSTRAINT_49;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<T_SHUKIN_RECORD>> getKeys() {
        return Arrays.<UniqueKey<T_SHUKIN_RECORD>>asList(Keys.CONSTRAINT_49, Keys.UK_63RAV1TUOYJH43EG9APMB9RKG);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<T_SHUKIN_RECORD, ?>> getReferences() {
        return Arrays.<ForeignKey<T_SHUKIN_RECORD, ?>>asList(Keys.FKP2XBWCE1FSSLKBIMFR4Q5KBN2, Keys.FK8XTLQQPNCUKA4NHMFXRVX3MH2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_SHUKIN as(String alias) {
        return new T_SHUKIN(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_SHUKIN as(Name alias) {
        return new T_SHUKIN(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public T_SHUKIN rename(String name) {
        return new T_SHUKIN(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public T_SHUKIN rename(Name name) {
        return new T_SHUKIN(name, null);
    }
}
