/*
 * This file is generated by jOOQ.
*/
package com.showka.table.public_.tables;


import com.showka.table.public_.Keys;
import com.showka.table.public_.Public;
import com.showka.table.public_.tables.records.T_SHOHIN_IDO_RECORD;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T_SHOHIN_IDO extends TableImpl<T_SHOHIN_IDO_RECORD> {

    private static final long serialVersionUID = 1341654333;

    /**
     * The reference instance of <code>PUBLIC.T_SHOHIN_IDO</code>
     */
    public static final T_SHOHIN_IDO t_shohin_ido = new T_SHOHIN_IDO();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<T_SHOHIN_IDO_RECORD> getRecordType() {
        return T_SHOHIN_IDO_RECORD.class;
    }

    /**
     * The column <code>PUBLIC.T_SHOHIN_IDO.ID</code>.
     */
    public final TableField<T_SHOHIN_IDO_RECORD, String> id = createField("ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_SHOHIN_IDO.CREATE_FUNCTION</code>.
     */
    public final TableField<T_SHOHIN_IDO_RECORD, String> create_function = createField("CREATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.T_SHOHIN_IDO.CREATE_TIMESTAMP</code>.
     */
    public final TableField<T_SHOHIN_IDO_RECORD, LocalDateTime> create_timestamp = createField("CREATE_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.T_SHOHIN_IDO.CREATE_USER_ID</code>.
     */
    public final TableField<T_SHOHIN_IDO_RECORD, String> create_user_id = createField("CREATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.T_SHOHIN_IDO.RECORD_ID</code>.
     */
    public final TableField<T_SHOHIN_IDO_RECORD, String> record_id = createField("RECORD_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_SHOHIN_IDO.UPDATE_FUNCTION</code>.
     */
    public final TableField<T_SHOHIN_IDO_RECORD, String> update_function = createField("UPDATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.T_SHOHIN_IDO.UPDATE_TIMESTAMP</code>.
     */
    public final TableField<T_SHOHIN_IDO_RECORD, LocalDateTime> update_timestamp = createField("UPDATE_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.T_SHOHIN_IDO.UPDATE_USER_ID</code>.
     */
    public final TableField<T_SHOHIN_IDO_RECORD, String> update_user_id = createField("UPDATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.T_SHOHIN_IDO.VERSION</code>.
     */
    public final TableField<T_SHOHIN_IDO_RECORD, Integer> version = createField("VERSION", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>PUBLIC.T_SHOHIN_IDO.BUSHO_ID</code>.
     */
    public final TableField<T_SHOHIN_IDO_RECORD, String> busho_id = createField("BUSHO_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_SHOHIN_IDO.DATE</code>.
     */
    public final TableField<T_SHOHIN_IDO_RECORD, LocalDateTime> date = createField("DATE", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_SHOHIN_IDO.KUBUN</code>.
     */
    public final TableField<T_SHOHIN_IDO_RECORD, String> kubun = createField("KUBUN", org.jooq.impl.SQLDataType.VARCHAR(2).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_SHOHIN_IDO.SAGYO_TIMESTAMP</code>.
     */
    public final TableField<T_SHOHIN_IDO_RECORD, LocalDateTime> sagyo_timestamp = createField("SAGYO_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>PUBLIC.T_SHOHIN_IDO</code> table reference
     */
    public T_SHOHIN_IDO() {
        this(DSL.name("T_SHOHIN_IDO"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.T_SHOHIN_IDO</code> table reference
     */
    public T_SHOHIN_IDO(String alias) {
        this(DSL.name(alias), t_shohin_ido);
    }

    /**
     * Create an aliased <code>PUBLIC.T_SHOHIN_IDO</code> table reference
     */
    public T_SHOHIN_IDO(Name alias) {
        this(alias, t_shohin_ido);
    }

    private T_SHOHIN_IDO(Name alias, Table<T_SHOHIN_IDO_RECORD> aliased) {
        this(alias, aliased, null);
    }

    private T_SHOHIN_IDO(Name alias, Table<T_SHOHIN_IDO_RECORD> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<T_SHOHIN_IDO_RECORD> getPrimaryKey() {
        return Keys.CONSTRAINT_1E;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<T_SHOHIN_IDO_RECORD>> getKeys() {
        return Arrays.<UniqueKey<T_SHOHIN_IDO_RECORD>>asList(Keys.CONSTRAINT_1E, Keys.UK_9HUM7RYAHI4JAIGE2V6TD9M13);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<T_SHOHIN_IDO_RECORD, ?>> getReferences() {
        return Arrays.<ForeignKey<T_SHOHIN_IDO_RECORD, ?>>asList(Keys.FKK5EMLYFTBF5PBADDC4QFNMGLH);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_SHOHIN_IDO as(String alias) {
        return new T_SHOHIN_IDO(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_SHOHIN_IDO as(Name alias) {
        return new T_SHOHIN_IDO(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public T_SHOHIN_IDO rename(String name) {
        return new T_SHOHIN_IDO(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public T_SHOHIN_IDO rename(Name name) {
        return new T_SHOHIN_IDO(name, null);
    }
}
