/*
 * This file is generated by jOOQ.
*/
package com.showka.table.public_.tables;


import com.showka.table.public_.Keys;
import com.showka.table.public_.Public;
import com.showka.table.public_.tables.records.T_URIAGE_MEISAI_RECORD;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T_URIAGE_MEISAI extends TableImpl<T_URIAGE_MEISAI_RECORD> {

    private static final long serialVersionUID = -1791128090;

    /**
     * The reference instance of <code>PUBLIC.T_URIAGE_MEISAI</code>
     */
    public static final T_URIAGE_MEISAI t_uriage_meisai = new T_URIAGE_MEISAI();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<T_URIAGE_MEISAI_RECORD> getRecordType() {
        return T_URIAGE_MEISAI_RECORD.class;
    }

    /**
     * The column <code>PUBLIC.T_URIAGE_MEISAI.MEISAI_NUMBER</code>.
     */
    public final TableField<T_URIAGE_MEISAI_RECORD, Integer> meisai_number = createField("MEISAI_NUMBER", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_URIAGE_MEISAI.URIAGE_ID</code>.
     */
    public final TableField<T_URIAGE_MEISAI_RECORD, String> uriage_id = createField("URIAGE_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_URIAGE_MEISAI.CREATE_FUNCTION</code>.
     */
    public final TableField<T_URIAGE_MEISAI_RECORD, String> create_function = createField("CREATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.T_URIAGE_MEISAI.CREATE_TIMESTAMP</code>.
     */
    public final TableField<T_URIAGE_MEISAI_RECORD, LocalDateTime> create_timestamp = createField("CREATE_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.T_URIAGE_MEISAI.CREATE_USER_ID</code>.
     */
    public final TableField<T_URIAGE_MEISAI_RECORD, String> create_user_id = createField("CREATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.T_URIAGE_MEISAI.RECORD_ID</code>.
     */
    public final TableField<T_URIAGE_MEISAI_RECORD, String> record_id = createField("RECORD_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_URIAGE_MEISAI.UPDATE_FUNCTION</code>.
     */
    public final TableField<T_URIAGE_MEISAI_RECORD, String> update_function = createField("UPDATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.T_URIAGE_MEISAI.UPDATE_TIMESTAMP</code>.
     */
    public final TableField<T_URIAGE_MEISAI_RECORD, LocalDateTime> update_timestamp = createField("UPDATE_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.T_URIAGE_MEISAI.UPDATE_USER_ID</code>.
     */
    public final TableField<T_URIAGE_MEISAI_RECORD, String> update_user_id = createField("UPDATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.T_URIAGE_MEISAI.VERSION</code>.
     */
    public final TableField<T_URIAGE_MEISAI_RECORD, Integer> version = createField("VERSION", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>PUBLIC.T_URIAGE_MEISAI.HANBAI_NUMBER</code>.
     */
    public final TableField<T_URIAGE_MEISAI_RECORD, Integer> hanbai_number = createField("HANBAI_NUMBER", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_URIAGE_MEISAI.HANBAI_TANKA</code>.
     */
    public final TableField<T_URIAGE_MEISAI_RECORD, Integer> hanbai_tanka = createField("HANBAI_TANKA", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_URIAGE_MEISAI.SHOHIN_ID</code>.
     */
    public final TableField<T_URIAGE_MEISAI_RECORD, String> shohin_id = createField("SHOHIN_ID", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>PUBLIC.T_URIAGE_MEISAI</code> table reference
     */
    public T_URIAGE_MEISAI() {
        this(DSL.name("T_URIAGE_MEISAI"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.T_URIAGE_MEISAI</code> table reference
     */
    public T_URIAGE_MEISAI(String alias) {
        this(DSL.name(alias), t_uriage_meisai);
    }

    /**
     * Create an aliased <code>PUBLIC.T_URIAGE_MEISAI</code> table reference
     */
    public T_URIAGE_MEISAI(Name alias) {
        this(alias, t_uriage_meisai);
    }

    private T_URIAGE_MEISAI(Name alias, Table<T_URIAGE_MEISAI_RECORD> aliased) {
        this(alias, aliased, null);
    }

    private T_URIAGE_MEISAI(Name alias, Table<T_URIAGE_MEISAI_RECORD> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<T_URIAGE_MEISAI_RECORD> getPrimaryKey() {
        return Keys.CONSTRAINT_B;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<T_URIAGE_MEISAI_RECORD>> getKeys() {
        return Arrays.<UniqueKey<T_URIAGE_MEISAI_RECORD>>asList(Keys.CONSTRAINT_B, Keys.UK_QRBW4ETEB9S2JK3SPMEXAULIG);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<T_URIAGE_MEISAI_RECORD, ?>> getReferences() {
        return Arrays.<ForeignKey<T_URIAGE_MEISAI_RECORD, ?>>asList(Keys.FKEFJRU4SE98KKBOBDKHDJC8IIM, Keys.FKR12W6PQB2GNMH56OFRHY0LOSC);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_URIAGE_MEISAI as(String alias) {
        return new T_URIAGE_MEISAI(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_URIAGE_MEISAI as(Name alias) {
        return new T_URIAGE_MEISAI(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public T_URIAGE_MEISAI rename(String name) {
        return new T_URIAGE_MEISAI(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public T_URIAGE_MEISAI rename(Name name) {
        return new T_URIAGE_MEISAI(name, null);
    }
}
