/*
 * This file is generated by jOOQ.
*/
package com.showka.table.public_.tables;


import com.showka.table.public_.Keys;
import com.showka.table.public_.Public;
import com.showka.table.public_.tables.records.T_URIKAKE_MISEIKYU_RECORD;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T_URIKAKE_MISEIKYU extends TableImpl<T_URIKAKE_MISEIKYU_RECORD> {

    private static final long serialVersionUID = -120713552;

    /**
     * The reference instance of <code>PUBLIC.T_URIKAKE_MISEIKYU</code>
     */
    public static final T_URIKAKE_MISEIKYU t_urikake_miseikyu = new T_URIKAKE_MISEIKYU();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<T_URIKAKE_MISEIKYU_RECORD> getRecordType() {
        return T_URIKAKE_MISEIKYU_RECORD.class;
    }

    /**
     * The column <code>PUBLIC.T_URIKAKE_MISEIKYU.URIKAKE_ID</code>.
     */
    public final TableField<T_URIKAKE_MISEIKYU_RECORD, String> urikake_id = createField("URIKAKE_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_URIKAKE_MISEIKYU.CREATE_FUNCTION</code>.
     */
    public final TableField<T_URIKAKE_MISEIKYU_RECORD, String> create_function = createField("CREATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.T_URIKAKE_MISEIKYU.CREATE_TIMESTAMP</code>.
     */
    public final TableField<T_URIKAKE_MISEIKYU_RECORD, LocalDateTime> create_timestamp = createField("CREATE_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.T_URIKAKE_MISEIKYU.CREATE_USER_ID</code>.
     */
    public final TableField<T_URIKAKE_MISEIKYU_RECORD, String> create_user_id = createField("CREATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.T_URIKAKE_MISEIKYU.RECORD_ID</code>.
     */
    public final TableField<T_URIKAKE_MISEIKYU_RECORD, String> record_id = createField("RECORD_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.T_URIKAKE_MISEIKYU.UPDATE_FUNCTION</code>.
     */
    public final TableField<T_URIKAKE_MISEIKYU_RECORD, String> update_function = createField("UPDATE_FUNCTION", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.T_URIKAKE_MISEIKYU.UPDATE_TIMESTAMP</code>.
     */
    public final TableField<T_URIKAKE_MISEIKYU_RECORD, LocalDateTime> update_timestamp = createField("UPDATE_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.T_URIKAKE_MISEIKYU.UPDATE_USER_ID</code>.
     */
    public final TableField<T_URIKAKE_MISEIKYU_RECORD, String> update_user_id = createField("UPDATE_USER_ID", org.jooq.impl.SQLDataType.VARCHAR(2147483647).nullable(false).defaultValue(org.jooq.impl.DSL.field("'default'", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>PUBLIC.T_URIKAKE_MISEIKYU.VERSION</code>.
     */
    public final TableField<T_URIKAKE_MISEIKYU_RECORD, Integer> version = createField("VERSION", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>PUBLIC.T_URIKAKE_MISEIKYU</code> table reference
     */
    public T_URIKAKE_MISEIKYU() {
        this(DSL.name("T_URIKAKE_MISEIKYU"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.T_URIKAKE_MISEIKYU</code> table reference
     */
    public T_URIKAKE_MISEIKYU(String alias) {
        this(DSL.name(alias), t_urikake_miseikyu);
    }

    /**
     * Create an aliased <code>PUBLIC.T_URIKAKE_MISEIKYU</code> table reference
     */
    public T_URIKAKE_MISEIKYU(Name alias) {
        this(alias, t_urikake_miseikyu);
    }

    private T_URIKAKE_MISEIKYU(Name alias, Table<T_URIKAKE_MISEIKYU_RECORD> aliased) {
        this(alias, aliased, null);
    }

    private T_URIKAKE_MISEIKYU(Name alias, Table<T_URIKAKE_MISEIKYU_RECORD> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<T_URIKAKE_MISEIKYU_RECORD> getPrimaryKey() {
        return Keys.CONSTRAINT_BB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<T_URIKAKE_MISEIKYU_RECORD>> getKeys() {
        return Arrays.<UniqueKey<T_URIKAKE_MISEIKYU_RECORD>>asList(Keys.CONSTRAINT_BB, Keys.UK_QQQ9XMCG11YHYLQRK9YA2XCVV);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<T_URIKAKE_MISEIKYU_RECORD, ?>> getReferences() {
        return Arrays.<ForeignKey<T_URIKAKE_MISEIKYU_RECORD, ?>>asList(Keys.FKLBHEN31UWEW3FUTAVYU3EA9UI);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_URIKAKE_MISEIKYU as(String alias) {
        return new T_URIKAKE_MISEIKYU(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_URIKAKE_MISEIKYU as(Name alias) {
        return new T_URIKAKE_MISEIKYU(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public T_URIKAKE_MISEIKYU rename(String name) {
        return new T_URIKAKE_MISEIKYU(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public T_URIKAKE_MISEIKYU rename(Name name) {
        return new T_URIKAKE_MISEIKYU(name, null);
    }
}
