/*
 * This file is generated by jOOQ.
*/
package com.showka.table.public_.tables.records;


import com.showka.table.public_.tables.T_KESHIKOMI;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T_KESHIKOMI_RECORD extends UpdatableRecordImpl<T_KESHIKOMI_RECORD> implements Record14<String, String, LocalDateTime, String, String, String, LocalDateTime, String, Integer, LocalDateTime, Integer, String, LocalDateTime, String> {

    private static final long serialVersionUID = -1230367210;

    /**
     * Setter for <code>PUBLIC.T_KESHIKOMI.ID</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.T_KESHIKOMI.ID</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>PUBLIC.T_KESHIKOMI.CREATE_FUNCTION</code>.
     */
    public void setCreateFunction(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.T_KESHIKOMI.CREATE_FUNCTION</code>.
     */
    public String getCreateFunction() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.T_KESHIKOMI.CREATE_TIMESTAMP</code>.
     */
    public void setCreateTimestamp(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.T_KESHIKOMI.CREATE_TIMESTAMP</code>.
     */
    public LocalDateTime getCreateTimestamp() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>PUBLIC.T_KESHIKOMI.CREATE_USER_ID</code>.
     */
    public void setCreateUserId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.T_KESHIKOMI.CREATE_USER_ID</code>.
     */
    public String getCreateUserId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.T_KESHIKOMI.RECORD_ID</code>.
     */
    public void setRecordId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.T_KESHIKOMI.RECORD_ID</code>.
     */
    public String getRecordId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.T_KESHIKOMI.UPDATE_FUNCTION</code>.
     */
    public void setUpdateFunction(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.T_KESHIKOMI.UPDATE_FUNCTION</code>.
     */
    public String getUpdateFunction() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.T_KESHIKOMI.UPDATE_TIMESTAMP</code>.
     */
    public void setUpdateTimestamp(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.T_KESHIKOMI.UPDATE_TIMESTAMP</code>.
     */
    public LocalDateTime getUpdateTimestamp() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>PUBLIC.T_KESHIKOMI.UPDATE_USER_ID</code>.
     */
    public void setUpdateUserId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.T_KESHIKOMI.UPDATE_USER_ID</code>.
     */
    public String getUpdateUserId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>PUBLIC.T_KESHIKOMI.VERSION</code>.
     */
    public void setVersion(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.T_KESHIKOMI.VERSION</code>.
     */
    public Integer getVersion() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>PUBLIC.T_KESHIKOMI.DATE</code>.
     */
    public void setDate(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>PUBLIC.T_KESHIKOMI.DATE</code>.
     */
    public LocalDateTime getDate() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>PUBLIC.T_KESHIKOMI.KINGAKU</code>.
     */
    public void setKingaku(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>PUBLIC.T_KESHIKOMI.KINGAKU</code>.
     */
    public Integer getKingaku() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>PUBLIC.T_KESHIKOMI.NYUKIN_ID</code>.
     */
    public void setNyukinId(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>PUBLIC.T_KESHIKOMI.NYUKIN_ID</code>.
     */
    public String getNyukinId() {
        return (String) get(11);
    }

    /**
     * Setter for <code>PUBLIC.T_KESHIKOMI.TIMESTAMP</code>.
     */
    public void setTimestamp(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>PUBLIC.T_KESHIKOMI.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>PUBLIC.T_KESHIKOMI.URIKAKE_ID</code>.
     */
    public void setUrikakeId(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>PUBLIC.T_KESHIKOMI.URIKAKE_ID</code>.
     */
    public String getUrikakeId() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, String, LocalDateTime, String, String, String, LocalDateTime, String, Integer, LocalDateTime, Integer, String, LocalDateTime, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, String, LocalDateTime, String, String, String, LocalDateTime, String, Integer, LocalDateTime, Integer, String, LocalDateTime, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return T_KESHIKOMI.t_keshikomi.id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return T_KESHIKOMI.t_keshikomi.create_function;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field3() {
        return T_KESHIKOMI.t_keshikomi.create_timestamp;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return T_KESHIKOMI.t_keshikomi.create_user_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return T_KESHIKOMI.t_keshikomi.record_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return T_KESHIKOMI.t_keshikomi.update_function;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return T_KESHIKOMI.t_keshikomi.update_timestamp;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return T_KESHIKOMI.t_keshikomi.update_user_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return T_KESHIKOMI.t_keshikomi.version;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field10() {
        return T_KESHIKOMI.t_keshikomi.date;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return T_KESHIKOMI.t_keshikomi.kingaku;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return T_KESHIKOMI.t_keshikomi.nyukin_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field13() {
        return T_KESHIKOMI.t_keshikomi.timestamp;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return T_KESHIKOMI.t_keshikomi.urikake_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCreateFunction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component3() {
        return getCreateTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCreateUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getRecordId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUpdateFunction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component7() {
        return getUpdateTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getUpdateUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component10() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getKingaku();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getNyukinId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component13() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getUrikakeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCreateFunction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value3() {
        return getCreateTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCreateUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getRecordId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUpdateFunction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getUpdateTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUpdateUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value10() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getKingaku();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getNyukinId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value13() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getUrikakeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_KESHIKOMI_RECORD value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_KESHIKOMI_RECORD value2(String value) {
        setCreateFunction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_KESHIKOMI_RECORD value3(LocalDateTime value) {
        setCreateTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_KESHIKOMI_RECORD value4(String value) {
        setCreateUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_KESHIKOMI_RECORD value5(String value) {
        setRecordId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_KESHIKOMI_RECORD value6(String value) {
        setUpdateFunction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_KESHIKOMI_RECORD value7(LocalDateTime value) {
        setUpdateTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_KESHIKOMI_RECORD value8(String value) {
        setUpdateUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_KESHIKOMI_RECORD value9(Integer value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_KESHIKOMI_RECORD value10(LocalDateTime value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_KESHIKOMI_RECORD value11(Integer value) {
        setKingaku(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_KESHIKOMI_RECORD value12(String value) {
        setNyukinId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_KESHIKOMI_RECORD value13(LocalDateTime value) {
        setTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_KESHIKOMI_RECORD value14(String value) {
        setUrikakeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_KESHIKOMI_RECORD values(String value1, String value2, LocalDateTime value3, String value4, String value5, String value6, LocalDateTime value7, String value8, Integer value9, LocalDateTime value10, Integer value11, String value12, LocalDateTime value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached T_KESHIKOMI_RECORD
     */
    public T_KESHIKOMI_RECORD() {
        super(T_KESHIKOMI.t_keshikomi);
    }

    /**
     * Create a detached, initialised T_KESHIKOMI_RECORD
     */
    public T_KESHIKOMI_RECORD(String id, String create_function, LocalDateTime create_timestamp, String create_user_id, String record_id, String update_function, LocalDateTime update_timestamp, String update_user_id, Integer version, LocalDateTime date, Integer kingaku, String nyukin_id, LocalDateTime timestamp, String urikake_id) {
        super(T_KESHIKOMI.t_keshikomi);

        set(0, id);
        set(1, create_function);
        set(2, create_timestamp);
        set(3, create_user_id);
        set(4, record_id);
        set(5, update_function);
        set(6, update_timestamp);
        set(7, update_user_id);
        set(8, version);
        set(9, date);
        set(10, kingaku);
        set(11, nyukin_id);
        set(12, timestamp);
        set(13, urikake_id);
    }
}
