/*
 * This file is generated by jOOQ.
*/
package com.showka.table.public_.tables.records;


import com.showka.table.public_.tables.T_NYUKIN;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T_NYUKIN_RECORD extends UpdatableRecordImpl<T_NYUKIN_RECORD> implements Record14<String, String, LocalDateTime, String, String, String, LocalDateTime, String, Integer, String, LocalDateTime, Integer, String, String> {

    private static final long serialVersionUID = 296420316;

    /**
     * Setter for <code>PUBLIC.T_NYUKIN.ID</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.T_NYUKIN.ID</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>PUBLIC.T_NYUKIN.CREATE_FUNCTION</code>.
     */
    public void setCreateFunction(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.T_NYUKIN.CREATE_FUNCTION</code>.
     */
    public String getCreateFunction() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.T_NYUKIN.CREATE_TIMESTAMP</code>.
     */
    public void setCreateTimestamp(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.T_NYUKIN.CREATE_TIMESTAMP</code>.
     */
    public LocalDateTime getCreateTimestamp() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>PUBLIC.T_NYUKIN.CREATE_USER_ID</code>.
     */
    public void setCreateUserId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.T_NYUKIN.CREATE_USER_ID</code>.
     */
    public String getCreateUserId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.T_NYUKIN.RECORD_ID</code>.
     */
    public void setRecordId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.T_NYUKIN.RECORD_ID</code>.
     */
    public String getRecordId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.T_NYUKIN.UPDATE_FUNCTION</code>.
     */
    public void setUpdateFunction(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.T_NYUKIN.UPDATE_FUNCTION</code>.
     */
    public String getUpdateFunction() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.T_NYUKIN.UPDATE_TIMESTAMP</code>.
     */
    public void setUpdateTimestamp(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.T_NYUKIN.UPDATE_TIMESTAMP</code>.
     */
    public LocalDateTime getUpdateTimestamp() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>PUBLIC.T_NYUKIN.UPDATE_USER_ID</code>.
     */
    public void setUpdateUserId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.T_NYUKIN.UPDATE_USER_ID</code>.
     */
    public String getUpdateUserId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>PUBLIC.T_NYUKIN.VERSION</code>.
     */
    public void setVersion(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.T_NYUKIN.VERSION</code>.
     */
    public Integer getVersion() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>PUBLIC.T_NYUKIN.BUSHO_ID</code>.
     */
    public void setBushoId(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>PUBLIC.T_NYUKIN.BUSHO_ID</code>.
     */
    public String getBushoId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>PUBLIC.T_NYUKIN.DATE</code>.
     */
    public void setDate(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>PUBLIC.T_NYUKIN.DATE</code>.
     */
    public LocalDateTime getDate() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>PUBLIC.T_NYUKIN.KINGAKU</code>.
     */
    public void setKingaku(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>PUBLIC.T_NYUKIN.KINGAKU</code>.
     */
    public Integer getKingaku() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>PUBLIC.T_NYUKIN.KOKYAKU_ID</code>.
     */
    public void setKokyakuId(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>PUBLIC.T_NYUKIN.KOKYAKU_ID</code>.
     */
    public String getKokyakuId() {
        return (String) get(12);
    }

    /**
     * Setter for <code>PUBLIC.T_NYUKIN.NYUKIN_HOHO_KUBUN</code>.
     */
    public void setNyukinHohoKubun(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>PUBLIC.T_NYUKIN.NYUKIN_HOHO_KUBUN</code>.
     */
    public String getNyukinHohoKubun() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, String, LocalDateTime, String, String, String, LocalDateTime, String, Integer, String, LocalDateTime, Integer, String, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, String, LocalDateTime, String, String, String, LocalDateTime, String, Integer, String, LocalDateTime, Integer, String, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return T_NYUKIN.t_nyukin.id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return T_NYUKIN.t_nyukin.create_function;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field3() {
        return T_NYUKIN.t_nyukin.create_timestamp;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return T_NYUKIN.t_nyukin.create_user_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return T_NYUKIN.t_nyukin.record_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return T_NYUKIN.t_nyukin.update_function;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return T_NYUKIN.t_nyukin.update_timestamp;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return T_NYUKIN.t_nyukin.update_user_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return T_NYUKIN.t_nyukin.version;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return T_NYUKIN.t_nyukin.busho_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field11() {
        return T_NYUKIN.t_nyukin.date;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return T_NYUKIN.t_nyukin.kingaku;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return T_NYUKIN.t_nyukin.kokyaku_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return T_NYUKIN.t_nyukin.nyukin_hoho_kubun;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCreateFunction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component3() {
        return getCreateTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCreateUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getRecordId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUpdateFunction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component7() {
        return getUpdateTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getUpdateUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getBushoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component11() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component12() {
        return getKingaku();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getKokyakuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getNyukinHohoKubun();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCreateFunction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value3() {
        return getCreateTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCreateUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getRecordId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUpdateFunction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getUpdateTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUpdateUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getBushoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value11() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getKingaku();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getKokyakuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getNyukinHohoKubun();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_NYUKIN_RECORD value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_NYUKIN_RECORD value2(String value) {
        setCreateFunction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_NYUKIN_RECORD value3(LocalDateTime value) {
        setCreateTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_NYUKIN_RECORD value4(String value) {
        setCreateUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_NYUKIN_RECORD value5(String value) {
        setRecordId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_NYUKIN_RECORD value6(String value) {
        setUpdateFunction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_NYUKIN_RECORD value7(LocalDateTime value) {
        setUpdateTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_NYUKIN_RECORD value8(String value) {
        setUpdateUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_NYUKIN_RECORD value9(Integer value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_NYUKIN_RECORD value10(String value) {
        setBushoId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_NYUKIN_RECORD value11(LocalDateTime value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_NYUKIN_RECORD value12(Integer value) {
        setKingaku(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_NYUKIN_RECORD value13(String value) {
        setKokyakuId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_NYUKIN_RECORD value14(String value) {
        setNyukinHohoKubun(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_NYUKIN_RECORD values(String value1, String value2, LocalDateTime value3, String value4, String value5, String value6, LocalDateTime value7, String value8, Integer value9, String value10, LocalDateTime value11, Integer value12, String value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached T_NYUKIN_RECORD
     */
    public T_NYUKIN_RECORD() {
        super(T_NYUKIN.t_nyukin);
    }

    /**
     * Create a detached, initialised T_NYUKIN_RECORD
     */
    public T_NYUKIN_RECORD(String id, String create_function, LocalDateTime create_timestamp, String create_user_id, String record_id, String update_function, LocalDateTime update_timestamp, String update_user_id, Integer version, String busho_id, LocalDateTime date, Integer kingaku, String kokyaku_id, String nyukin_hoho_kubun) {
        super(T_NYUKIN.t_nyukin);

        set(0, id);
        set(1, create_function);
        set(2, create_timestamp);
        set(3, create_user_id);
        set(4, record_id);
        set(5, update_function);
        set(6, update_timestamp);
        set(7, update_user_id);
        set(8, version);
        set(9, busho_id);
        set(10, date);
        set(11, kingaku);
        set(12, kokyaku_id);
        set(13, nyukin_hoho_kubun);
    }
}
