/*
 * This file is generated by jOOQ.
*/
package com.showka.table.public_.tables.records;


import com.showka.table.public_.tables.T_SEIKYU;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Record2;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T_SEIKYU_RECORD extends UpdatableRecordImpl<T_SEIKYU_RECORD> implements Record11<String, LocalDateTime, String, LocalDateTime, String, String, String, LocalDateTime, String, Integer, LocalDateTime> {

    private static final long serialVersionUID = -295864901;

    /**
     * Setter for <code>PUBLIC.T_SEIKYU.KOKYAKU_ID</code>.
     */
    public void setKokyakuId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.T_SEIKYU.KOKYAKU_ID</code>.
     */
    public String getKokyakuId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>PUBLIC.T_SEIKYU.SEIKYU_DATE</code>.
     */
    public void setSeikyuDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.T_SEIKYU.SEIKYU_DATE</code>.
     */
    public LocalDateTime getSeikyuDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>PUBLIC.T_SEIKYU.CREATE_FUNCTION</code>.
     */
    public void setCreateFunction(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.T_SEIKYU.CREATE_FUNCTION</code>.
     */
    public String getCreateFunction() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.T_SEIKYU.CREATE_TIMESTAMP</code>.
     */
    public void setCreateTimestamp(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.T_SEIKYU.CREATE_TIMESTAMP</code>.
     */
    public LocalDateTime getCreateTimestamp() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>PUBLIC.T_SEIKYU.CREATE_USER_ID</code>.
     */
    public void setCreateUserId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.T_SEIKYU.CREATE_USER_ID</code>.
     */
    public String getCreateUserId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.T_SEIKYU.RECORD_ID</code>.
     */
    public void setRecordId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.T_SEIKYU.RECORD_ID</code>.
     */
    public String getRecordId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.T_SEIKYU.UPDATE_FUNCTION</code>.
     */
    public void setUpdateFunction(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.T_SEIKYU.UPDATE_FUNCTION</code>.
     */
    public String getUpdateFunction() {
        return (String) get(6);
    }

    /**
     * Setter for <code>PUBLIC.T_SEIKYU.UPDATE_TIMESTAMP</code>.
     */
    public void setUpdateTimestamp(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.T_SEIKYU.UPDATE_TIMESTAMP</code>.
     */
    public LocalDateTime getUpdateTimestamp() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>PUBLIC.T_SEIKYU.UPDATE_USER_ID</code>.
     */
    public void setUpdateUserId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.T_SEIKYU.UPDATE_USER_ID</code>.
     */
    public String getUpdateUserId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>PUBLIC.T_SEIKYU.VERSION</code>.
     */
    public void setVersion(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>PUBLIC.T_SEIKYU.VERSION</code>.
     */
    public Integer getVersion() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>PUBLIC.T_SEIKYU.SHIHARAI_DATE</code>.
     */
    public void setShiharaiDate(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>PUBLIC.T_SEIKYU.SHIHARAI_DATE</code>.
     */
    public LocalDateTime getShiharaiDate() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, LocalDateTime> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, LocalDateTime, String, LocalDateTime, String, String, String, LocalDateTime, String, Integer, LocalDateTime> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, LocalDateTime, String, LocalDateTime, String, String, String, LocalDateTime, String, Integer, LocalDateTime> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return T_SEIKYU.t_seikyu.kokyaku_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field2() {
        return T_SEIKYU.t_seikyu.seikyu_date;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return T_SEIKYU.t_seikyu.create_function;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return T_SEIKYU.t_seikyu.create_timestamp;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return T_SEIKYU.t_seikyu.create_user_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return T_SEIKYU.t_seikyu.record_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return T_SEIKYU.t_seikyu.update_function;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return T_SEIKYU.t_seikyu.update_timestamp;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return T_SEIKYU.t_seikyu.update_user_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return T_SEIKYU.t_seikyu.version;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field11() {
        return T_SEIKYU.t_seikyu.shiharai_date;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getKokyakuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component2() {
        return getSeikyuDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCreateFunction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component4() {
        return getCreateTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCreateUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getRecordId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getUpdateFunction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component8() {
        return getUpdateTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getUpdateUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component11() {
        return getShiharaiDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getKokyakuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value2() {
        return getSeikyuDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCreateFunction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getCreateTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCreateUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getRecordId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUpdateFunction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getUpdateTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getUpdateUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value11() {
        return getShiharaiDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_SEIKYU_RECORD value1(String value) {
        setKokyakuId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_SEIKYU_RECORD value2(LocalDateTime value) {
        setSeikyuDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_SEIKYU_RECORD value3(String value) {
        setCreateFunction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_SEIKYU_RECORD value4(LocalDateTime value) {
        setCreateTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_SEIKYU_RECORD value5(String value) {
        setCreateUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_SEIKYU_RECORD value6(String value) {
        setRecordId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_SEIKYU_RECORD value7(String value) {
        setUpdateFunction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_SEIKYU_RECORD value8(LocalDateTime value) {
        setUpdateTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_SEIKYU_RECORD value9(String value) {
        setUpdateUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_SEIKYU_RECORD value10(Integer value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_SEIKYU_RECORD value11(LocalDateTime value) {
        setShiharaiDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_SEIKYU_RECORD values(String value1, LocalDateTime value2, String value3, LocalDateTime value4, String value5, String value6, String value7, LocalDateTime value8, String value9, Integer value10, LocalDateTime value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached T_SEIKYU_RECORD
     */
    public T_SEIKYU_RECORD() {
        super(T_SEIKYU.t_seikyu);
    }

    /**
     * Create a detached, initialised T_SEIKYU_RECORD
     */
    public T_SEIKYU_RECORD(String kokyaku_id, LocalDateTime seikyu_date, String create_function, LocalDateTime create_timestamp, String create_user_id, String record_id, String update_function, LocalDateTime update_timestamp, String update_user_id, Integer version, LocalDateTime shiharai_date) {
        super(T_SEIKYU.t_seikyu);

        set(0, kokyaku_id);
        set(1, seikyu_date);
        set(2, create_function);
        set(3, create_timestamp);
        set(4, create_user_id);
        set(5, record_id);
        set(6, update_function);
        set(7, update_timestamp);
        set(8, update_user_id);
        set(9, version);
        set(10, shiharai_date);
    }
}
