/*
 * This file is generated by jOOQ.
*/
package com.showka.table.public_.tables.records;


import com.showka.table.public_.tables.T_URIAGE_MEISAI;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Record2;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T_URIAGE_MEISAI_RECORD extends UpdatableRecordImpl<T_URIAGE_MEISAI_RECORD> implements Record13<Integer, String, String, LocalDateTime, String, String, String, LocalDateTime, String, Integer, Integer, Integer, String> {

    private static final long serialVersionUID = -1735280225;

    /**
     * Setter for <code>PUBLIC.T_URIAGE_MEISAI.MEISAI_NUMBER</code>.
     */
    public void setMeisaiNumber(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.T_URIAGE_MEISAI.MEISAI_NUMBER</code>.
     */
    public Integer getMeisaiNumber() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.T_URIAGE_MEISAI.URIAGE_ID</code>.
     */
    public void setUriageId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.T_URIAGE_MEISAI.URIAGE_ID</code>.
     */
    public String getUriageId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.T_URIAGE_MEISAI.CREATE_FUNCTION</code>.
     */
    public void setCreateFunction(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.T_URIAGE_MEISAI.CREATE_FUNCTION</code>.
     */
    public String getCreateFunction() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.T_URIAGE_MEISAI.CREATE_TIMESTAMP</code>.
     */
    public void setCreateTimestamp(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.T_URIAGE_MEISAI.CREATE_TIMESTAMP</code>.
     */
    public LocalDateTime getCreateTimestamp() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>PUBLIC.T_URIAGE_MEISAI.CREATE_USER_ID</code>.
     */
    public void setCreateUserId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.T_URIAGE_MEISAI.CREATE_USER_ID</code>.
     */
    public String getCreateUserId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.T_URIAGE_MEISAI.RECORD_ID</code>.
     */
    public void setRecordId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.T_URIAGE_MEISAI.RECORD_ID</code>.
     */
    public String getRecordId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.T_URIAGE_MEISAI.UPDATE_FUNCTION</code>.
     */
    public void setUpdateFunction(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.T_URIAGE_MEISAI.UPDATE_FUNCTION</code>.
     */
    public String getUpdateFunction() {
        return (String) get(6);
    }

    /**
     * Setter for <code>PUBLIC.T_URIAGE_MEISAI.UPDATE_TIMESTAMP</code>.
     */
    public void setUpdateTimestamp(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.T_URIAGE_MEISAI.UPDATE_TIMESTAMP</code>.
     */
    public LocalDateTime getUpdateTimestamp() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>PUBLIC.T_URIAGE_MEISAI.UPDATE_USER_ID</code>.
     */
    public void setUpdateUserId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.T_URIAGE_MEISAI.UPDATE_USER_ID</code>.
     */
    public String getUpdateUserId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>PUBLIC.T_URIAGE_MEISAI.VERSION</code>.
     */
    public void setVersion(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>PUBLIC.T_URIAGE_MEISAI.VERSION</code>.
     */
    public Integer getVersion() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>PUBLIC.T_URIAGE_MEISAI.HANBAI_NUMBER</code>.
     */
    public void setHanbaiNumber(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>PUBLIC.T_URIAGE_MEISAI.HANBAI_NUMBER</code>.
     */
    public Integer getHanbaiNumber() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>PUBLIC.T_URIAGE_MEISAI.HANBAI_TANKA</code>.
     */
    public void setHanbaiTanka(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>PUBLIC.T_URIAGE_MEISAI.HANBAI_TANKA</code>.
     */
    public Integer getHanbaiTanka() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>PUBLIC.T_URIAGE_MEISAI.SHOHIN_ID</code>.
     */
    public void setShohinId(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>PUBLIC.T_URIAGE_MEISAI.SHOHIN_ID</code>.
     */
    public String getShohinId() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, LocalDateTime, String, String, String, LocalDateTime, String, Integer, Integer, Integer, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, LocalDateTime, String, String, String, LocalDateTime, String, Integer, Integer, Integer, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return T_URIAGE_MEISAI.t_uriage_meisai.meisai_number;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return T_URIAGE_MEISAI.t_uriage_meisai.uriage_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return T_URIAGE_MEISAI.t_uriage_meisai.create_function;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return T_URIAGE_MEISAI.t_uriage_meisai.create_timestamp;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return T_URIAGE_MEISAI.t_uriage_meisai.create_user_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return T_URIAGE_MEISAI.t_uriage_meisai.record_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return T_URIAGE_MEISAI.t_uriage_meisai.update_function;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return T_URIAGE_MEISAI.t_uriage_meisai.update_timestamp;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return T_URIAGE_MEISAI.t_uriage_meisai.update_user_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return T_URIAGE_MEISAI.t_uriage_meisai.version;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return T_URIAGE_MEISAI.t_uriage_meisai.hanbai_number;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return T_URIAGE_MEISAI.t_uriage_meisai.hanbai_tanka;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return T_URIAGE_MEISAI.t_uriage_meisai.shohin_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getMeisaiNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUriageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCreateFunction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component4() {
        return getCreateTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCreateUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getRecordId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getUpdateFunction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component8() {
        return getUpdateTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getUpdateUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getHanbaiNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component12() {
        return getHanbaiTanka();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getShohinId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getMeisaiNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUriageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCreateFunction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getCreateTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCreateUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getRecordId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUpdateFunction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getUpdateTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getUpdateUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getHanbaiNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getHanbaiTanka();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getShohinId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_URIAGE_MEISAI_RECORD value1(Integer value) {
        setMeisaiNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_URIAGE_MEISAI_RECORD value2(String value) {
        setUriageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_URIAGE_MEISAI_RECORD value3(String value) {
        setCreateFunction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_URIAGE_MEISAI_RECORD value4(LocalDateTime value) {
        setCreateTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_URIAGE_MEISAI_RECORD value5(String value) {
        setCreateUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_URIAGE_MEISAI_RECORD value6(String value) {
        setRecordId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_URIAGE_MEISAI_RECORD value7(String value) {
        setUpdateFunction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_URIAGE_MEISAI_RECORD value8(LocalDateTime value) {
        setUpdateTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_URIAGE_MEISAI_RECORD value9(String value) {
        setUpdateUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_URIAGE_MEISAI_RECORD value10(Integer value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_URIAGE_MEISAI_RECORD value11(Integer value) {
        setHanbaiNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_URIAGE_MEISAI_RECORD value12(Integer value) {
        setHanbaiTanka(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_URIAGE_MEISAI_RECORD value13(String value) {
        setShohinId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_URIAGE_MEISAI_RECORD values(Integer value1, String value2, String value3, LocalDateTime value4, String value5, String value6, String value7, LocalDateTime value8, String value9, Integer value10, Integer value11, Integer value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached T_URIAGE_MEISAI_RECORD
     */
    public T_URIAGE_MEISAI_RECORD() {
        super(T_URIAGE_MEISAI.t_uriage_meisai);
    }

    /**
     * Create a detached, initialised T_URIAGE_MEISAI_RECORD
     */
    public T_URIAGE_MEISAI_RECORD(Integer meisai_number, String uriage_id, String create_function, LocalDateTime create_timestamp, String create_user_id, String record_id, String update_function, LocalDateTime update_timestamp, String update_user_id, Integer version, Integer hanbai_number, Integer hanbai_tanka, String shohin_id) {
        super(T_URIAGE_MEISAI.t_uriage_meisai);

        set(0, meisai_number);
        set(1, uriage_id);
        set(2, create_function);
        set(3, create_timestamp);
        set(4, create_user_id);
        set(5, record_id);
        set(6, update_function);
        set(7, update_timestamp);
        set(8, update_user_id);
        set(9, version);
        set(10, hanbai_number);
        set(11, hanbai_tanka);
        set(12, shohin_id);
    }
}
