/*
 * This file is generated by jOOQ.
*/
package com.showka.table.public_;


import com.showka.table.public_.tables.C_URIAGE;
import com.showka.table.public_.tables.J_SHOHIN_IDO_URIAGE;
import com.showka.table.public_.tables.M_BUSHO;
import com.showka.table.public_.tables.M_BUSHO_DATE;
import com.showka.table.public_.tables.M_KOKYAKU;
import com.showka.table.public_.tables.M_NYUKIN_KAKE_INFO;
import com.showka.table.public_.tables.M_SHAIN;
import com.showka.table.public_.tables.M_SHOHIN;
import com.showka.table.public_.tables.M_USER;
import com.showka.table.public_.tables.R_URIAGE;
import com.showka.table.public_.tables.R_URIAGE_KEIJO;
import com.showka.table.public_.tables.R_URIAGE_KEIJO_TEISEI;
import com.showka.table.public_.tables.R_URIAGE_MEISAI;
import com.showka.table.public_.tables.T_SEIKYU;
import com.showka.table.public_.tables.T_SEIKYU_MEISAI;
import com.showka.table.public_.tables.T_SHOHIN_IDO;
import com.showka.table.public_.tables.T_SHOHIN_IDO_MEISAI;
import com.showka.table.public_.tables.T_SHOHIN_ZAIKO;
import com.showka.table.public_.tables.T_URIAGE;
import com.showka.table.public_.tables.T_URIAGE_MEISAI;
import com.showka.table.public_.tables.T_URIKAKE;
import com.showka.table.public_.tables.records.C_URIAGE_RECORD;
import com.showka.table.public_.tables.records.J_SHOHIN_IDO_URIAGE_RECORD;
import com.showka.table.public_.tables.records.M_BUSHO_DATE_RECORD;
import com.showka.table.public_.tables.records.M_BUSHO_RECORD;
import com.showka.table.public_.tables.records.M_KOKYAKU_RECORD;
import com.showka.table.public_.tables.records.M_NYUKIN_KAKE_INFO_RECORD;
import com.showka.table.public_.tables.records.M_SHAIN_RECORD;
import com.showka.table.public_.tables.records.M_SHOHIN_RECORD;
import com.showka.table.public_.tables.records.M_USER_RECORD;
import com.showka.table.public_.tables.records.R_URIAGE_KEIJO_RECORD;
import com.showka.table.public_.tables.records.R_URIAGE_KEIJO_TEISEI_RECORD;
import com.showka.table.public_.tables.records.R_URIAGE_MEISAI_RECORD;
import com.showka.table.public_.tables.records.R_URIAGE_RECORD;
import com.showka.table.public_.tables.records.T_SEIKYU_MEISAI_RECORD;
import com.showka.table.public_.tables.records.T_SEIKYU_RECORD;
import com.showka.table.public_.tables.records.T_SHOHIN_IDO_MEISAI_RECORD;
import com.showka.table.public_.tables.records.T_SHOHIN_IDO_RECORD;
import com.showka.table.public_.tables.records.T_SHOHIN_ZAIKO_RECORD;
import com.showka.table.public_.tables.records.T_URIAGE_MEISAI_RECORD;
import com.showka.table.public_.tables.records.T_URIAGE_RECORD;
import com.showka.table.public_.tables.records.T_URIKAKE_RECORD;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<C_URIAGE_RECORD> CONSTRAINT_6 = UniqueKeys0.CONSTRAINT_6;
    public static final UniqueKey<C_URIAGE_RECORD> UK_C90UBJW54JK7MVI3FGQ9NA2QU = UniqueKeys0.UK_C90UBJW54JK7MVI3FGQ9NA2QU;
    public static final UniqueKey<J_SHOHIN_IDO_URIAGE_RECORD> CONSTRAINT_2 = UniqueKeys0.CONSTRAINT_2;
    public static final UniqueKey<J_SHOHIN_IDO_URIAGE_RECORD> UK_CFXPYU7SU1PV9WO2AUTSACG0I = UniqueKeys0.UK_CFXPYU7SU1PV9WO2AUTSACG0I;
    public static final UniqueKey<M_BUSHO_RECORD> CONSTRAINT_8 = UniqueKeys0.CONSTRAINT_8;
    public static final UniqueKey<M_BUSHO_RECORD> UK_5BY1GUP4TXK8FK16KGF8MPF38 = UniqueKeys0.UK_5BY1GUP4TXK8FK16KGF8MPF38;
    public static final UniqueKey<M_BUSHO_DATE_RECORD> CONSTRAINT_E = UniqueKeys0.CONSTRAINT_E;
    public static final UniqueKey<M_BUSHO_DATE_RECORD> UK_KGBIV56WTAT03W6I4V383FU7A = UniqueKeys0.UK_KGBIV56WTAT03W6I4V383FU7A;
    public static final UniqueKey<M_KOKYAKU_RECORD> CONSTRAINT_2F = UniqueKeys0.CONSTRAINT_2F;
    public static final UniqueKey<M_KOKYAKU_RECORD> UK_7UBB14KG5P5MBCYPBMRVYR7HO = UniqueKeys0.UK_7UBB14KG5P5MBCYPBMRVYR7HO;
    public static final UniqueKey<M_NYUKIN_KAKE_INFO_RECORD> CONSTRAINT_E7 = UniqueKeys0.CONSTRAINT_E7;
    public static final UniqueKey<M_NYUKIN_KAKE_INFO_RECORD> UK_L40OVD3L702092P9XG88XU4VX = UniqueKeys0.UK_L40OVD3L702092P9XG88XU4VX;
    public static final UniqueKey<M_SHAIN_RECORD> CONSTRAINT_9 = UniqueKeys0.CONSTRAINT_9;
    public static final UniqueKey<M_SHAIN_RECORD> UK_81PKBX9M7PBAFUMTCUKHTOOBH = UniqueKeys0.UK_81PKBX9M7PBAFUMTCUKHTOOBH;
    public static final UniqueKey<M_SHOHIN_RECORD> CONSTRAINT_7 = UniqueKeys0.CONSTRAINT_7;
    public static final UniqueKey<M_SHOHIN_RECORD> UK_QQ0UP8I0X3HO6U8CL0QEMQ4QJ = UniqueKeys0.UK_QQ0UP8I0X3HO6U8CL0QEMQ4QJ;
    public static final UniqueKey<M_USER_RECORD> CONSTRAINT_88 = UniqueKeys0.CONSTRAINT_88;
    public static final UniqueKey<M_USER_RECORD> UK_E0AD43H00N5AJYKDHEM6ODJ79 = UniqueKeys0.UK_E0AD43H00N5AJYKDHEM6ODJ79;
    public static final UniqueKey<M_USER_RECORD> UK_BRMB54LD0GQSTOGMB812XW951 = UniqueKeys0.UK_BRMB54LD0GQSTOGMB812XW951;
    public static final UniqueKey<R_URIAGE_RECORD> CONSTRAINT_7D = UniqueKeys0.CONSTRAINT_7D;
    public static final UniqueKey<R_URIAGE_RECORD> UK_3PUXJQQMYDE93SCH3O89I3UV7 = UniqueKeys0.UK_3PUXJQQMYDE93SCH3O89I3UV7;
    public static final UniqueKey<R_URIAGE_KEIJO_RECORD> CONSTRAINT_21 = UniqueKeys0.CONSTRAINT_21;
    public static final UniqueKey<R_URIAGE_KEIJO_RECORD> UK_68YGMNT83I8TJ9VCTJUJ7DNOH = UniqueKeys0.UK_68YGMNT83I8TJ9VCTJUJ7DNOH;
    public static final UniqueKey<R_URIAGE_KEIJO_TEISEI_RECORD> CONSTRAINT_F = UniqueKeys0.CONSTRAINT_F;
    public static final UniqueKey<R_URIAGE_KEIJO_TEISEI_RECORD> UK_5FQTU9VF1ITABDUFF88E46ALY = UniqueKeys0.UK_5FQTU9VF1ITABDUFF88E46ALY;
    public static final UniqueKey<R_URIAGE_MEISAI_RECORD> CONSTRAINT_5 = UniqueKeys0.CONSTRAINT_5;
    public static final UniqueKey<R_URIAGE_MEISAI_RECORD> UK_DHV8J2AK6U0FRWNAWO7MHUDEP = UniqueKeys0.UK_DHV8J2AK6U0FRWNAWO7MHUDEP;
    public static final UniqueKey<T_SEIKYU_RECORD> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;
    public static final UniqueKey<T_SEIKYU_RECORD> UK_4SCPAF4QMJRAM1VXMKUYJ269J = UniqueKeys0.UK_4SCPAF4QMJRAM1VXMKUYJ269J;
    public static final UniqueKey<T_SEIKYU_MEISAI_RECORD> CONSTRAINT_ED = UniqueKeys0.CONSTRAINT_ED;
    public static final UniqueKey<T_SEIKYU_MEISAI_RECORD> UK_R4P4GM00P10V2HXDQSBCNVPP0 = UniqueKeys0.UK_R4P4GM00P10V2HXDQSBCNVPP0;
    public static final UniqueKey<T_SHOHIN_IDO_RECORD> CONSTRAINT_1 = UniqueKeys0.CONSTRAINT_1;
    public static final UniqueKey<T_SHOHIN_IDO_RECORD> UK_9HUM7RYAHI4JAIGE2V6TD9M13 = UniqueKeys0.UK_9HUM7RYAHI4JAIGE2V6TD9M13;
    public static final UniqueKey<T_SHOHIN_IDO_MEISAI_RECORD> CONSTRAINT_25 = UniqueKeys0.CONSTRAINT_25;
    public static final UniqueKey<T_SHOHIN_IDO_MEISAI_RECORD> UK_QMKOJB8N58COAAOK60IQVBJ5B = UniqueKeys0.UK_QMKOJB8N58COAAOK60IQVBJ5B;
    public static final UniqueKey<T_SHOHIN_ZAIKO_RECORD> CONSTRAINT_78 = UniqueKeys0.CONSTRAINT_78;
    public static final UniqueKey<T_SHOHIN_ZAIKO_RECORD> UK_97I9YEJ178G3KQCKRFJ4GJH0N = UniqueKeys0.UK_97I9YEJ178G3KQCKRFJ4GJH0N;
    public static final UniqueKey<T_URIAGE_RECORD> CONSTRAINT_4D = UniqueKeys0.CONSTRAINT_4D;
    public static final UniqueKey<T_URIAGE_RECORD> UK_9F7L0VVJA040FK4UIR58IBQUN = UniqueKeys0.UK_9F7L0VVJA040FK4UIR58IBQUN;
    public static final UniqueKey<T_URIAGE_MEISAI_RECORD> CONSTRAINT_B = UniqueKeys0.CONSTRAINT_B;
    public static final UniqueKey<T_URIAGE_MEISAI_RECORD> UK_QRBW4ETEB9S2JK3SPMEXAULIG = UniqueKeys0.UK_QRBW4ETEB9S2JK3SPMEXAULIG;
    public static final UniqueKey<T_URIKAKE_RECORD> CONSTRAINT_53 = UniqueKeys0.CONSTRAINT_53;
    public static final UniqueKey<T_URIKAKE_RECORD> UK_3RCPSMXXRKKRO42FWTDIPIAXB = UniqueKeys0.UK_3RCPSMXXRKKRO42FWTDIPIAXB;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<C_URIAGE_RECORD, T_URIAGE_RECORD> FKEDPVU5W0BXSMRNXCHN19IA4KK = ForeignKeys0.FKEDPVU5W0BXSMRNXCHN19IA4KK;
    public static final ForeignKey<J_SHOHIN_IDO_URIAGE_RECORD, T_SHOHIN_IDO_RECORD> FK5DYE4WJDXP0GYE240FAHRWIYY = ForeignKeys0.FK5DYE4WJDXP0GYE240FAHRWIYY;
    public static final ForeignKey<J_SHOHIN_IDO_URIAGE_RECORD, T_URIAGE_RECORD> FKTFEGJY18RHN048QJ3D5GH9SRV = ForeignKeys0.FKTFEGJY18RHN048QJ3D5GH9SRV;
    public static final ForeignKey<M_KOKYAKU_RECORD, M_BUSHO_RECORD> FKM9UAXXH78HO91ET19MDDUBHGL = ForeignKeys0.FKM9UAXXH78HO91ET19MDDUBHGL;
    public static final ForeignKey<M_NYUKIN_KAKE_INFO_RECORD, M_KOKYAKU_RECORD> FK78QFGCRWR2OUM5CYOICF0ULU4 = ForeignKeys0.FK78QFGCRWR2OUM5CYOICF0ULU4;
    public static final ForeignKey<M_SHAIN_RECORD, M_BUSHO_RECORD> FK6EXWC57AN76H9BS794TJGTUGN = ForeignKeys0.FK6EXWC57AN76H9BS794TJGTUGN;
    public static final ForeignKey<R_URIAGE_RECORD, T_URIAGE_RECORD> FKPA4RJI1OV770T37MNYHLVHTY1 = ForeignKeys0.FKPA4RJI1OV770T37MNYHLVHTY1;
    public static final ForeignKey<R_URIAGE_KEIJO_RECORD, R_URIAGE_RECORD> FKH0U4RF1JDXDX32VNB3O7FU8PH = ForeignKeys0.FKH0U4RF1JDXDX32VNB3O7FU8PH;
    public static final ForeignKey<R_URIAGE_KEIJO_RECORD, M_BUSHO_RECORD> FK88YWWSH8XTTSGK28INR0I5POH = ForeignKeys0.FK88YWWSH8XTTSGK28INR0I5POH;
    public static final ForeignKey<R_URIAGE_KEIJO_TEISEI_RECORD, R_URIAGE_KEIJO_RECORD> FKMHVV9FBVRGL5J34H408W7LXQF = ForeignKeys0.FKMHVV9FBVRGL5J34H408W7LXQF;
    public static final ForeignKey<R_URIAGE_KEIJO_TEISEI_RECORD, R_URIAGE_RECORD> FKJ7YBAXR6IN6VUA1KLM2I10YEK = ForeignKeys0.FKJ7YBAXR6IN6VUA1KLM2I10YEK;
    public static final ForeignKey<R_URIAGE_MEISAI_RECORD, R_URIAGE_RECORD> FKBIIJRTBUHPP07F2W0VMMA3P8F = ForeignKeys0.FKBIIJRTBUHPP07F2W0VMMA3P8F;
    public static final ForeignKey<R_URIAGE_MEISAI_RECORD, M_SHOHIN_RECORD> FKMGXRSBS5HMJ32AOXEMX6UROQR = ForeignKeys0.FKMGXRSBS5HMJ32AOXEMX6UROQR;
    public static final ForeignKey<T_SEIKYU_RECORD, M_KOKYAKU_RECORD> FKS8KT4C3Q2N4GLUH51SN6LLX73 = ForeignKeys0.FKS8KT4C3Q2N4GLUH51SN6LLX73;
    public static final ForeignKey<T_SEIKYU_MEISAI_RECORD, T_SEIKYU_RECORD> FKIJ280RY31WVS01KUE3MGM0XP0 = ForeignKeys0.FKIJ280RY31WVS01KUE3MGM0XP0;
    public static final ForeignKey<T_SEIKYU_MEISAI_RECORD, T_URIKAKE_RECORD> FK9AXJO7K5P73YYEWXSIC6HT04W = ForeignKeys0.FK9AXJO7K5P73YYEWXSIC6HT04W;
    public static final ForeignKey<T_SHOHIN_IDO_RECORD, M_BUSHO_RECORD> FKK5EMLYFTBF5PBADDC4QFNMGLH = ForeignKeys0.FKK5EMLYFTBF5PBADDC4QFNMGLH;
    public static final ForeignKey<T_SHOHIN_IDO_MEISAI_RECORD, T_SHOHIN_IDO_RECORD> FKP0LRETW08695Q1FOIS2EK6Q6B = ForeignKeys0.FKP0LRETW08695Q1FOIS2EK6Q6B;
    public static final ForeignKey<T_SHOHIN_IDO_MEISAI_RECORD, M_SHOHIN_RECORD> FKNYESTD5U0GAEDM2AUNTF943D1 = ForeignKeys0.FKNYESTD5U0GAEDM2AUNTF943D1;
    public static final ForeignKey<T_SHOHIN_ZAIKO_RECORD, M_SHOHIN_RECORD> FKTKU4TUGX74WKRAT36T4WWNWEB = ForeignKeys0.FKTKU4TUGX74WKRAT36T4WWNWEB;
    public static final ForeignKey<T_URIAGE_RECORD, M_KOKYAKU_RECORD> FK12V4JQQCK1CDREC88PF37AU7D = ForeignKeys0.FK12V4JQQCK1CDREC88PF37AU7D;
    public static final ForeignKey<T_URIAGE_RECORD, C_URIAGE_RECORD> FK6SW82826AYV5RUVOM3UGBU6JK = ForeignKeys0.FK6SW82826AYV5RUVOM3UGBU6JK;
    public static final ForeignKey<T_URIAGE_MEISAI_RECORD, T_URIAGE_RECORD> FKEFJRU4SE98KKBOBDKHDJC8IIM = ForeignKeys0.FKEFJRU4SE98KKBOBDKHDJC8IIM;
    public static final ForeignKey<T_URIAGE_MEISAI_RECORD, M_SHOHIN_RECORD> FKR12W6PQB2GNMH56OFRHY0LOSC = ForeignKeys0.FKR12W6PQB2GNMH56OFRHY0LOSC;
    public static final ForeignKey<T_URIKAKE_RECORD, T_URIAGE_RECORD> FK5QEL4CGVEMJKPVIBO5647PES1 = ForeignKeys0.FK5QEL4CGVEMJKPVIBO5647PES1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<C_URIAGE_RECORD> CONSTRAINT_6 = Internal.createUniqueKey(C_URIAGE.c_uriage, "CONSTRAINT_6", C_URIAGE.c_uriage.uriage_id);
        public static final UniqueKey<C_URIAGE_RECORD> UK_C90UBJW54JK7MVI3FGQ9NA2QU = Internal.createUniqueKey(C_URIAGE.c_uriage, "UK_C90UBJW54JK7MVI3FGQ9NA2QU", C_URIAGE.c_uriage.record_id);
        public static final UniqueKey<J_SHOHIN_IDO_URIAGE_RECORD> CONSTRAINT_2 = Internal.createUniqueKey(J_SHOHIN_IDO_URIAGE.j_shohin_ido_uriage, "CONSTRAINT_2", J_SHOHIN_IDO_URIAGE.j_shohin_ido_uriage.shohin_ido_id);
        public static final UniqueKey<J_SHOHIN_IDO_URIAGE_RECORD> UK_CFXPYU7SU1PV9WO2AUTSACG0I = Internal.createUniqueKey(J_SHOHIN_IDO_URIAGE.j_shohin_ido_uriage, "UK_CFXPYU7SU1PV9WO2AUTSACG0I", J_SHOHIN_IDO_URIAGE.j_shohin_ido_uriage.record_id);
        public static final UniqueKey<M_BUSHO_RECORD> CONSTRAINT_8 = Internal.createUniqueKey(M_BUSHO.m_busho, "CONSTRAINT_8", M_BUSHO.m_busho.code);
        public static final UniqueKey<M_BUSHO_RECORD> UK_5BY1GUP4TXK8FK16KGF8MPF38 = Internal.createUniqueKey(M_BUSHO.m_busho, "UK_5BY1GUP4TXK8FK16KGF8MPF38", M_BUSHO.m_busho.record_id);
        public static final UniqueKey<M_BUSHO_DATE_RECORD> CONSTRAINT_E = Internal.createUniqueKey(M_BUSHO_DATE.m_busho_date, "CONSTRAINT_E", M_BUSHO_DATE.m_busho_date.busho_id);
        public static final UniqueKey<M_BUSHO_DATE_RECORD> UK_KGBIV56WTAT03W6I4V383FU7A = Internal.createUniqueKey(M_BUSHO_DATE.m_busho_date, "UK_KGBIV56WTAT03W6I4V383FU7A", M_BUSHO_DATE.m_busho_date.record_id);
        public static final UniqueKey<M_KOKYAKU_RECORD> CONSTRAINT_2F = Internal.createUniqueKey(M_KOKYAKU.m_kokyaku, "CONSTRAINT_2F", M_KOKYAKU.m_kokyaku.code);
        public static final UniqueKey<M_KOKYAKU_RECORD> UK_7UBB14KG5P5MBCYPBMRVYR7HO = Internal.createUniqueKey(M_KOKYAKU.m_kokyaku, "UK_7UBB14KG5P5MBCYPBMRVYR7HO", M_KOKYAKU.m_kokyaku.record_id);
        public static final UniqueKey<M_NYUKIN_KAKE_INFO_RECORD> CONSTRAINT_E7 = Internal.createUniqueKey(M_NYUKIN_KAKE_INFO.m_nyukin_kake_info, "CONSTRAINT_E7", M_NYUKIN_KAKE_INFO.m_nyukin_kake_info.kokyaku_id);
        public static final UniqueKey<M_NYUKIN_KAKE_INFO_RECORD> UK_L40OVD3L702092P9XG88XU4VX = Internal.createUniqueKey(M_NYUKIN_KAKE_INFO.m_nyukin_kake_info, "UK_L40OVD3L702092P9XG88XU4VX", M_NYUKIN_KAKE_INFO.m_nyukin_kake_info.record_id);
        public static final UniqueKey<M_SHAIN_RECORD> CONSTRAINT_9 = Internal.createUniqueKey(M_SHAIN.m_shain, "CONSTRAINT_9", M_SHAIN.m_shain.code);
        public static final UniqueKey<M_SHAIN_RECORD> UK_81PKBX9M7PBAFUMTCUKHTOOBH = Internal.createUniqueKey(M_SHAIN.m_shain, "UK_81PKBX9M7PBAFUMTCUKHTOOBH", M_SHAIN.m_shain.record_id);
        public static final UniqueKey<M_SHOHIN_RECORD> CONSTRAINT_7 = Internal.createUniqueKey(M_SHOHIN.m_shohin, "CONSTRAINT_7", M_SHOHIN.m_shohin.code);
        public static final UniqueKey<M_SHOHIN_RECORD> UK_QQ0UP8I0X3HO6U8CL0QEMQ4QJ = Internal.createUniqueKey(M_SHOHIN.m_shohin, "UK_QQ0UP8I0X3HO6U8CL0QEMQ4QJ", M_SHOHIN.m_shohin.record_id);
        public static final UniqueKey<M_USER_RECORD> CONSTRAINT_88 = Internal.createUniqueKey(M_USER.m_user, "CONSTRAINT_88", M_USER.m_user.id);
        public static final UniqueKey<M_USER_RECORD> UK_E0AD43H00N5AJYKDHEM6ODJ79 = Internal.createUniqueKey(M_USER.m_user, "UK_E0AD43H00N5AJYKDHEM6ODJ79", M_USER.m_user.record_id);
        public static final UniqueKey<M_USER_RECORD> UK_BRMB54LD0GQSTOGMB812XW951 = Internal.createUniqueKey(M_USER.m_user, "UK_BRMB54LD0GQSTOGMB812XW951", M_USER.m_user.username);
        public static final UniqueKey<R_URIAGE_RECORD> CONSTRAINT_7D = Internal.createUniqueKey(R_URIAGE.r_uriage, "CONSTRAINT_7D", R_URIAGE.r_uriage.keijo_date, R_URIAGE.r_uriage.uriage_id);
        public static final UniqueKey<R_URIAGE_RECORD> UK_3PUXJQQMYDE93SCH3O89I3UV7 = Internal.createUniqueKey(R_URIAGE.r_uriage, "UK_3PUXJQQMYDE93SCH3O89I3UV7", R_URIAGE.r_uriage.record_id);
        public static final UniqueKey<R_URIAGE_KEIJO_RECORD> CONSTRAINT_21 = Internal.createUniqueKey(R_URIAGE_KEIJO.r_uriage_keijo, "CONSTRAINT_21", R_URIAGE_KEIJO.r_uriage_keijo.uriage_rireki_id);
        public static final UniqueKey<R_URIAGE_KEIJO_RECORD> UK_68YGMNT83I8TJ9VCTJUJ7DNOH = Internal.createUniqueKey(R_URIAGE_KEIJO.r_uriage_keijo, "UK_68YGMNT83I8TJ9VCTJUJ7DNOH", R_URIAGE_KEIJO.r_uriage_keijo.record_id);
        public static final UniqueKey<R_URIAGE_KEIJO_TEISEI_RECORD> CONSTRAINT_F = Internal.createUniqueKey(R_URIAGE_KEIJO_TEISEI.r_uriage_keijo_teisei, "CONSTRAINT_F", R_URIAGE_KEIJO_TEISEI.r_uriage_keijo_teisei.uriage_keijo_id);
        public static final UniqueKey<R_URIAGE_KEIJO_TEISEI_RECORD> UK_5FQTU9VF1ITABDUFF88E46ALY = Internal.createUniqueKey(R_URIAGE_KEIJO_TEISEI.r_uriage_keijo_teisei, "UK_5FQTU9VF1ITABDUFF88E46ALY", R_URIAGE_KEIJO_TEISEI.r_uriage_keijo_teisei.record_id);
        public static final UniqueKey<R_URIAGE_MEISAI_RECORD> CONSTRAINT_5 = Internal.createUniqueKey(R_URIAGE_MEISAI.r_uriage_meisai, "CONSTRAINT_5", R_URIAGE_MEISAI.r_uriage_meisai.meisai_number, R_URIAGE_MEISAI.r_uriage_meisai.uriage_id);
        public static final UniqueKey<R_URIAGE_MEISAI_RECORD> UK_DHV8J2AK6U0FRWNAWO7MHUDEP = Internal.createUniqueKey(R_URIAGE_MEISAI.r_uriage_meisai, "UK_DHV8J2AK6U0FRWNAWO7MHUDEP", R_URIAGE_MEISAI.r_uriage_meisai.record_id);
        public static final UniqueKey<T_SEIKYU_RECORD> CONSTRAINT_4 = Internal.createUniqueKey(T_SEIKYU.t_seikyu, "CONSTRAINT_4", T_SEIKYU.t_seikyu.kokyaku_id, T_SEIKYU.t_seikyu.seikyu_date);
        public static final UniqueKey<T_SEIKYU_RECORD> UK_4SCPAF4QMJRAM1VXMKUYJ269J = Internal.createUniqueKey(T_SEIKYU.t_seikyu, "UK_4SCPAF4QMJRAM1VXMKUYJ269J", T_SEIKYU.t_seikyu.record_id);
        public static final UniqueKey<T_SEIKYU_MEISAI_RECORD> CONSTRAINT_ED = Internal.createUniqueKey(T_SEIKYU_MEISAI.t_seikyu_meisai, "CONSTRAINT_ED", T_SEIKYU_MEISAI.t_seikyu_meisai.seikyu_id, T_SEIKYU_MEISAI.t_seikyu_meisai.urikake_id);
        public static final UniqueKey<T_SEIKYU_MEISAI_RECORD> UK_R4P4GM00P10V2HXDQSBCNVPP0 = Internal.createUniqueKey(T_SEIKYU_MEISAI.t_seikyu_meisai, "UK_R4P4GM00P10V2HXDQSBCNVPP0", T_SEIKYU_MEISAI.t_seikyu_meisai.record_id);
        public static final UniqueKey<T_SHOHIN_IDO_RECORD> CONSTRAINT_1 = Internal.createUniqueKey(T_SHOHIN_IDO.t_shohin_ido, "CONSTRAINT_1", T_SHOHIN_IDO.t_shohin_ido.id);
        public static final UniqueKey<T_SHOHIN_IDO_RECORD> UK_9HUM7RYAHI4JAIGE2V6TD9M13 = Internal.createUniqueKey(T_SHOHIN_IDO.t_shohin_ido, "UK_9HUM7RYAHI4JAIGE2V6TD9M13", T_SHOHIN_IDO.t_shohin_ido.record_id);
        public static final UniqueKey<T_SHOHIN_IDO_MEISAI_RECORD> CONSTRAINT_25 = Internal.createUniqueKey(T_SHOHIN_IDO_MEISAI.t_shohin_ido_meisai, "CONSTRAINT_25", T_SHOHIN_IDO_MEISAI.t_shohin_ido_meisai.meisai_number, T_SHOHIN_IDO_MEISAI.t_shohin_ido_meisai.shohin_ido_id);
        public static final UniqueKey<T_SHOHIN_IDO_MEISAI_RECORD> UK_QMKOJB8N58COAAOK60IQVBJ5B = Internal.createUniqueKey(T_SHOHIN_IDO_MEISAI.t_shohin_ido_meisai, "UK_QMKOJB8N58COAAOK60IQVBJ5B", T_SHOHIN_IDO_MEISAI.t_shohin_ido_meisai.record_id);
        public static final UniqueKey<T_SHOHIN_ZAIKO_RECORD> CONSTRAINT_78 = Internal.createUniqueKey(T_SHOHIN_ZAIKO.t_shohin_zaiko, "CONSTRAINT_78", T_SHOHIN_ZAIKO.t_shohin_zaiko.busho_id, T_SHOHIN_ZAIKO.t_shohin_zaiko.eigyo_date, T_SHOHIN_ZAIKO.t_shohin_zaiko.shohin_id);
        public static final UniqueKey<T_SHOHIN_ZAIKO_RECORD> UK_97I9YEJ178G3KQCKRFJ4GJH0N = Internal.createUniqueKey(T_SHOHIN_ZAIKO.t_shohin_zaiko, "UK_97I9YEJ178G3KQCKRFJ4GJH0N", T_SHOHIN_ZAIKO.t_shohin_zaiko.record_id);
        public static final UniqueKey<T_URIAGE_RECORD> CONSTRAINT_4D = Internal.createUniqueKey(T_URIAGE.t_uriage, "CONSTRAINT_4D", T_URIAGE.t_uriage.denpyo_number, T_URIAGE.t_uriage.kokyaku_id);
        public static final UniqueKey<T_URIAGE_RECORD> UK_9F7L0VVJA040FK4UIR58IBQUN = Internal.createUniqueKey(T_URIAGE.t_uriage, "UK_9F7L0VVJA040FK4UIR58IBQUN", T_URIAGE.t_uriage.record_id);
        public static final UniqueKey<T_URIAGE_MEISAI_RECORD> CONSTRAINT_B = Internal.createUniqueKey(T_URIAGE_MEISAI.t_uriage_meisai, "CONSTRAINT_B", T_URIAGE_MEISAI.t_uriage_meisai.meisai_number, T_URIAGE_MEISAI.t_uriage_meisai.uriage_id);
        public static final UniqueKey<T_URIAGE_MEISAI_RECORD> UK_QRBW4ETEB9S2JK3SPMEXAULIG = Internal.createUniqueKey(T_URIAGE_MEISAI.t_uriage_meisai, "UK_QRBW4ETEB9S2JK3SPMEXAULIG", T_URIAGE_MEISAI.t_uriage_meisai.record_id);
        public static final UniqueKey<T_URIKAKE_RECORD> CONSTRAINT_53 = Internal.createUniqueKey(T_URIKAKE.t_urikake, "CONSTRAINT_53", T_URIKAKE.t_urikake.uriage_id);
        public static final UniqueKey<T_URIKAKE_RECORD> UK_3RCPSMXXRKKRO42FWTDIPIAXB = Internal.createUniqueKey(T_URIKAKE.t_urikake, "UK_3RCPSMXXRKKRO42FWTDIPIAXB", T_URIKAKE.t_urikake.record_id);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<C_URIAGE_RECORD, T_URIAGE_RECORD> FKEDPVU5W0BXSMRNXCHN19IA4KK = Internal.createForeignKey(com.showka.table.public_.Keys.UK_9F7L0VVJA040FK4UIR58IBQUN, C_URIAGE.c_uriage, "FKEDPVU5W0BXSMRNXCHN19IA4KK", C_URIAGE.c_uriage.uriage_id);
        public static final ForeignKey<J_SHOHIN_IDO_URIAGE_RECORD, T_SHOHIN_IDO_RECORD> FK5DYE4WJDXP0GYE240FAHRWIYY = Internal.createForeignKey(com.showka.table.public_.Keys.UK_9HUM7RYAHI4JAIGE2V6TD9M13, J_SHOHIN_IDO_URIAGE.j_shohin_ido_uriage, "FK5DYE4WJDXP0GYE240FAHRWIYY", J_SHOHIN_IDO_URIAGE.j_shohin_ido_uriage.shohin_ido_id);
        public static final ForeignKey<J_SHOHIN_IDO_URIAGE_RECORD, T_URIAGE_RECORD> FKTFEGJY18RHN048QJ3D5GH9SRV = Internal.createForeignKey(com.showka.table.public_.Keys.UK_9F7L0VVJA040FK4UIR58IBQUN, J_SHOHIN_IDO_URIAGE.j_shohin_ido_uriage, "FKTFEGJY18RHN048QJ3D5GH9SRV", J_SHOHIN_IDO_URIAGE.j_shohin_ido_uriage.uriage_id);
        public static final ForeignKey<M_KOKYAKU_RECORD, M_BUSHO_RECORD> FKM9UAXXH78HO91ET19MDDUBHGL = Internal.createForeignKey(com.showka.table.public_.Keys.UK_5BY1GUP4TXK8FK16KGF8MPF38, M_KOKYAKU.m_kokyaku, "FKM9UAXXH78HO91ET19MDDUBHGL", M_KOKYAKU.m_kokyaku.shukan_busho_id);
        public static final ForeignKey<M_NYUKIN_KAKE_INFO_RECORD, M_KOKYAKU_RECORD> FK78QFGCRWR2OUM5CYOICF0ULU4 = Internal.createForeignKey(com.showka.table.public_.Keys.UK_7UBB14KG5P5MBCYPBMRVYR7HO, M_NYUKIN_KAKE_INFO.m_nyukin_kake_info, "FK78QFGCRWR2OUM5CYOICF0ULU4", M_NYUKIN_KAKE_INFO.m_nyukin_kake_info.kokyaku_id);
        public static final ForeignKey<M_SHAIN_RECORD, M_BUSHO_RECORD> FK6EXWC57AN76H9BS794TJGTUGN = Internal.createForeignKey(com.showka.table.public_.Keys.UK_5BY1GUP4TXK8FK16KGF8MPF38, M_SHAIN.m_shain, "FK6EXWC57AN76H9BS794TJGTUGN", M_SHAIN.m_shain.shozoku_busho_id);
        public static final ForeignKey<R_URIAGE_RECORD, T_URIAGE_RECORD> FKPA4RJI1OV770T37MNYHLVHTY1 = Internal.createForeignKey(com.showka.table.public_.Keys.UK_9F7L0VVJA040FK4UIR58IBQUN, R_URIAGE.r_uriage, "FKPA4RJI1OV770T37MNYHLVHTY1", R_URIAGE.r_uriage.uriage_id);
        public static final ForeignKey<R_URIAGE_KEIJO_RECORD, R_URIAGE_RECORD> FKH0U4RF1JDXDX32VNB3O7FU8PH = Internal.createForeignKey(com.showka.table.public_.Keys.UK_3PUXJQQMYDE93SCH3O89I3UV7, R_URIAGE_KEIJO.r_uriage_keijo, "FKH0U4RF1JDXDX32VNB3O7FU8PH", R_URIAGE_KEIJO.r_uriage_keijo.uriage_rireki_id);
        public static final ForeignKey<R_URIAGE_KEIJO_RECORD, M_BUSHO_RECORD> FK88YWWSH8XTTSGK28INR0I5POH = Internal.createForeignKey(com.showka.table.public_.Keys.UK_5BY1GUP4TXK8FK16KGF8MPF38, R_URIAGE_KEIJO.r_uriage_keijo, "FK88YWWSH8XTTSGK28INR0I5POH", R_URIAGE_KEIJO.r_uriage_keijo.busho_id);
        public static final ForeignKey<R_URIAGE_KEIJO_TEISEI_RECORD, R_URIAGE_KEIJO_RECORD> FKMHVV9FBVRGL5J34H408W7LXQF = Internal.createForeignKey(com.showka.table.public_.Keys.UK_68YGMNT83I8TJ9VCTJUJ7DNOH, R_URIAGE_KEIJO_TEISEI.r_uriage_keijo_teisei, "FKMHVV9FBVRGL5J34H408W7LXQF", R_URIAGE_KEIJO_TEISEI.r_uriage_keijo_teisei.uriage_keijo_id);
        public static final ForeignKey<R_URIAGE_KEIJO_TEISEI_RECORD, R_URIAGE_RECORD> FKJ7YBAXR6IN6VUA1KLM2I10YEK = Internal.createForeignKey(com.showka.table.public_.Keys.UK_3PUXJQQMYDE93SCH3O89I3UV7, R_URIAGE_KEIJO_TEISEI.r_uriage_keijo_teisei, "FKJ7YBAXR6IN6VUA1KLM2I10YEK", R_URIAGE_KEIJO_TEISEI.r_uriage_keijo_teisei.uriage_rireki_id);
        public static final ForeignKey<R_URIAGE_MEISAI_RECORD, R_URIAGE_RECORD> FKBIIJRTBUHPP07F2W0VMMA3P8F = Internal.createForeignKey(com.showka.table.public_.Keys.UK_3PUXJQQMYDE93SCH3O89I3UV7, R_URIAGE_MEISAI.r_uriage_meisai, "FKBIIJRTBUHPP07F2W0VMMA3P8F", R_URIAGE_MEISAI.r_uriage_meisai.uriage_id);
        public static final ForeignKey<R_URIAGE_MEISAI_RECORD, M_SHOHIN_RECORD> FKMGXRSBS5HMJ32AOXEMX6UROQR = Internal.createForeignKey(com.showka.table.public_.Keys.UK_QQ0UP8I0X3HO6U8CL0QEMQ4QJ, R_URIAGE_MEISAI.r_uriage_meisai, "FKMGXRSBS5HMJ32AOXEMX6UROQR", R_URIAGE_MEISAI.r_uriage_meisai.shohin_id);
        public static final ForeignKey<T_SEIKYU_RECORD, M_KOKYAKU_RECORD> FKS8KT4C3Q2N4GLUH51SN6LLX73 = Internal.createForeignKey(com.showka.table.public_.Keys.UK_7UBB14KG5P5MBCYPBMRVYR7HO, T_SEIKYU.t_seikyu, "FKS8KT4C3Q2N4GLUH51SN6LLX73", T_SEIKYU.t_seikyu.kokyaku_id);
        public static final ForeignKey<T_SEIKYU_MEISAI_RECORD, T_SEIKYU_RECORD> FKIJ280RY31WVS01KUE3MGM0XP0 = Internal.createForeignKey(com.showka.table.public_.Keys.UK_4SCPAF4QMJRAM1VXMKUYJ269J, T_SEIKYU_MEISAI.t_seikyu_meisai, "FKIJ280RY31WVS01KUE3MGM0XP0", T_SEIKYU_MEISAI.t_seikyu_meisai.seikyu_id);
        public static final ForeignKey<T_SEIKYU_MEISAI_RECORD, T_URIKAKE_RECORD> FK9AXJO7K5P73YYEWXSIC6HT04W = Internal.createForeignKey(com.showka.table.public_.Keys.UK_3RCPSMXXRKKRO42FWTDIPIAXB, T_SEIKYU_MEISAI.t_seikyu_meisai, "FK9AXJO7K5P73YYEWXSIC6HT04W", T_SEIKYU_MEISAI.t_seikyu_meisai.urikake_id);
        public static final ForeignKey<T_SHOHIN_IDO_RECORD, M_BUSHO_RECORD> FKK5EMLYFTBF5PBADDC4QFNMGLH = Internal.createForeignKey(com.showka.table.public_.Keys.UK_5BY1GUP4TXK8FK16KGF8MPF38, T_SHOHIN_IDO.t_shohin_ido, "FKK5EMLYFTBF5PBADDC4QFNMGLH", T_SHOHIN_IDO.t_shohin_ido.busho_id);
        public static final ForeignKey<T_SHOHIN_IDO_MEISAI_RECORD, T_SHOHIN_IDO_RECORD> FKP0LRETW08695Q1FOIS2EK6Q6B = Internal.createForeignKey(com.showka.table.public_.Keys.UK_9HUM7RYAHI4JAIGE2V6TD9M13, T_SHOHIN_IDO_MEISAI.t_shohin_ido_meisai, "FKP0LRETW08695Q1FOIS2EK6Q6B", T_SHOHIN_IDO_MEISAI.t_shohin_ido_meisai.shohin_ido_id);
        public static final ForeignKey<T_SHOHIN_IDO_MEISAI_RECORD, M_SHOHIN_RECORD> FKNYESTD5U0GAEDM2AUNTF943D1 = Internal.createForeignKey(com.showka.table.public_.Keys.UK_QQ0UP8I0X3HO6U8CL0QEMQ4QJ, T_SHOHIN_IDO_MEISAI.t_shohin_ido_meisai, "FKNYESTD5U0GAEDM2AUNTF943D1", T_SHOHIN_IDO_MEISAI.t_shohin_ido_meisai.shohin_id);
        public static final ForeignKey<T_SHOHIN_ZAIKO_RECORD, M_SHOHIN_RECORD> FKTKU4TUGX74WKRAT36T4WWNWEB = Internal.createForeignKey(com.showka.table.public_.Keys.UK_QQ0UP8I0X3HO6U8CL0QEMQ4QJ, T_SHOHIN_ZAIKO.t_shohin_zaiko, "FKTKU4TUGX74WKRAT36T4WWNWEB", T_SHOHIN_ZAIKO.t_shohin_zaiko.shohin_id);
        public static final ForeignKey<T_URIAGE_RECORD, M_KOKYAKU_RECORD> FK12V4JQQCK1CDREC88PF37AU7D = Internal.createForeignKey(com.showka.table.public_.Keys.UK_7UBB14KG5P5MBCYPBMRVYR7HO, T_URIAGE.t_uriage, "FK12V4JQQCK1CDREC88PF37AU7D", T_URIAGE.t_uriage.kokyaku_id);
        public static final ForeignKey<T_URIAGE_RECORD, C_URIAGE_RECORD> FK6SW82826AYV5RUVOM3UGBU6JK = Internal.createForeignKey(com.showka.table.public_.Keys.CONSTRAINT_6, T_URIAGE.t_uriage, "FK6SW82826AYV5RUVOM3UGBU6JK", T_URIAGE.t_uriage.cancel_uriage_id);
        public static final ForeignKey<T_URIAGE_MEISAI_RECORD, T_URIAGE_RECORD> FKEFJRU4SE98KKBOBDKHDJC8IIM = Internal.createForeignKey(com.showka.table.public_.Keys.UK_9F7L0VVJA040FK4UIR58IBQUN, T_URIAGE_MEISAI.t_uriage_meisai, "FKEFJRU4SE98KKBOBDKHDJC8IIM", T_URIAGE_MEISAI.t_uriage_meisai.uriage_id);
        public static final ForeignKey<T_URIAGE_MEISAI_RECORD, M_SHOHIN_RECORD> FKR12W6PQB2GNMH56OFRHY0LOSC = Internal.createForeignKey(com.showka.table.public_.Keys.UK_QQ0UP8I0X3HO6U8CL0QEMQ4QJ, T_URIAGE_MEISAI.t_uriage_meisai, "FKR12W6PQB2GNMH56OFRHY0LOSC", T_URIAGE_MEISAI.t_uriage_meisai.shohin_id);
        public static final ForeignKey<T_URIKAKE_RECORD, T_URIAGE_RECORD> FK5QEL4CGVEMJKPVIBO5647PES1 = Internal.createForeignKey(com.showka.table.public_.Keys.UK_9F7L0VVJA040FK4UIR58IBQUN, T_URIKAKE.t_urikake, "FK5QEL4CGVEMJKPVIBO5647PES1", T_URIKAKE.t_urikake.uriage_id);
    }
}
